/*options ERRORABEND;*/
options compress=yes missing=0 errors=1 pageno=1;*/
/*OPTIONS SOURCE SOURCE2 MPRINT COMPRESS=yes;*/

libname kelvin "/gccdm/users/cbcfkhg";
libname ds_uat "/gccsan/unsecured/sasdata/cdm";

%let setdt=today();
%let yymm=2101;
%let MMM=01;
%let YYYY=2021;
%put &yymm;
%put &MMM;
%put &YYYY;
options datestyle=dmy;


%let setStartDT='01JAN2019'd;
%let setEndDT='31DEC2021'd;

/*
proc sql;
create table temp as
select * from ds_uat.cardscdm1807
where AMRL_SETUP_ACCOUNT = "0004119110100430799";

quit;
*/



PROC FORMAT;

VALUE $DECISION
"A" = "APPROVED"
"D" = "DECLINED"
"C" = "CANCELLED";

VALUE GROUP
1	= "GP 1: REG"
2	= "GP 2: SCORE"
3	= "GP 3: LATEST STATUS"
4	= "GP 4: PAYMENT HIST"
5	= "GP 5: OTHER DECLINES"
6	= "GP 6: REF REVIEW"
OTHER = "NOT-ASSIGNED";

VALUE $RSNCAT
'DI','DA','GA','GB','GC','GD','GE','GF','GG','GH','GI','GJ',
'GM','GN','J01','J10','DP','J20','J25','J67' 										= "GROUP 1: REGULATORY DECLINES"
'AA', 'XX'																			= "GROUP 2: SCORE DECLINES"
'ST','AS','N1','N2','OA','B1','B2','B3','BD','P1','P2','RG',
'RD','N6','N7','N8','N9', 'J64','J23','J53','J14','J65','J66','J54'					= "GROUP 3: DECLINED DUE TO LATEST STATUS/NEGATIVE STATUSES"
'N3','N4','N5','P3','P4','P5','PV'													= "GROUP 4: SYSTEM DECLINES DUE TO FAILURE OF PAYMENT HISTORY RULES"
OTHER																				= "GROUP 5: OTHER DECLINES"
'RY','J26','J27','J28','J60','J68','J61'											= "GROUP 6: DECLINES AFTER REFERRAL TO CREDIT REVIEW"
;

VALUE $RSNCAT_N
'DI','DA','DB','J01','J10','DP','J20','J25','J67' 									= "GROUP 1: REGULATORY DECLINES"
'GA','GB','GC','GD','GE','GF','GG','GH','GI','GJ','GM','GN'							= "GROUP 1A. REG (BTI/60DPD)"
'AA', 'XX'																			= "GROUP 2: SCORE DECLINES"
'ST','AS','N1','N2','OA','B1','B2','B3','BD','P1','P2','J64',
'J23','J53','J14','J65','J66','J54'													= "GROUP 3: DECLINED DUE TO LATEST STATUS/NEGATIVE STATUSES"
'RG','RD','N6','N7','N8','N9'														= "GROUP 3B: NEG STATUS (INT)" 
'N3','N4','N5','P3','P4','P5','PV'													= "GROUP 4: SYSTEM DECLINES DUE TO FAILURE OF PAYMENT HISTORY RULES"
OTHER																				= "GROUP 5: OTHER DECLINES"
'RY','J26','J27','J28','J60','J68','J61'											= "GROUP 6: DECLINES AFTER REFERRAL TO CREDIT REVIEW"
;

VALUE $RSNCDE
/* CODES USED BY SYS WEF 1SEP2010 (SYSTEM DECLINE REASONS)*/
'DI' = "DI - REGULATORY DECLINE – BELOW MIN INCOME"
'DA' = "DA - REGULATORY DECLINE – BELOW MIN AGE"
'DB' = "DB - REGULATORY DECLINE - CUST HAS RAS (INT/EXT)" /*Collin Added 29062015*/
'GA' = "GA - REGULATORY DECLINE - BTI/60DPD BELOW MIN INCOME" /*EZ ADDED 30042015*/
'GB' = "GB - REGULATORY DECLINE - BTI/60DPD NEGATIVE STATUS" /*EZ ADDED 30042015*/
'GC' = "GC - REGULATORY DECLINE - BTI/60DPD LATEST BTI RATIO" /*EZ ADDED 30042015*/
'GD' = "GD - REGULATORY DECLINE - BTI/60DPD BAD DEBT/DMP/LITI" /*EZ ADDED 30042015*/
'GE' = "GE - REGULATORY DECLINE - BTI/60DPD PAYMENT HIST/BLK CD" /*EZ ADDED 30042015*/
'GF' = "GF - REGULATORY DECLINE - BTI/60DPD LIMIT UTILIZATION" /*EZ ADDED 30042015*/
'GG' = "GG - REGULATORY DECLINE - BTI/60DPD BEHAVIORAL SCORE" /*EZ ADDED 30042015*/
'GH' = "GH - REGULATORY DECLINE - BTI/60DPD LATEST CB STAT/SCORE" /*EZ ADDED 30042015*/
'GI' = "GI - REGULATORY DECLINE - BTI/60DPD LAST Y MTH HIST/BTI" /*EZ ADDED 30042015*/
'GJ' = "GJ - REGULATORY DECLINE - BTI/60DPD OTHERS" /*EZ ADDED 30042015*/
'GM' = "GM - REGULATORY DECLINE - 60DPD SUSP FLAG" /*EZ ADDED 30042015*/
'GN' = "GN - REGULATORY DECLINE - BTI SUSP FLAG" /*EZ ADDED 30042015*/
'AA' = "AA - SCORE DECLINE - APPLICATION SCORE" 
'ST' = "ST - INTERNAL DECLINE – NEGATIVE CUSTOMER STATUS"
'AS' = "AS - INTERNAL DECLINE - ACCOUNT SIGNALS/RECALL DATE/JUDGEMENT DATE"
'N1' = "N1 - INTERNAL DECLINE - LATEST PAYMENT DELINQUENT (FROM NX)"
'N2' = "N2 - INTERNAL DECLINE - CURRENT V+ BLOCK CODES"
'OA' = "OA - INTERNAL DECLINE - DEFAULT RISK POOL"
'B1' = "B1 - CB DECLINE - RISK GRADE HZ (FOR CASHLINEPLUS INCL HH OR HX)" /*EZ AMENDED ON 30042015*/
'B2' = "B2 - CB DECLINE - RISK GRADE HH"
'B3' = "B3 - CB DECLINE - CB SCORE < 1600" 
'BD' = "BD - CB DECLINE - BAD DEBT RECORD OR DMP OR LITIGATION/BANKRUPT INDICATOR"
'P1' = "P1 - CB DECLINE - LATEST PAYMENT DELINQUENT"
'P2' = "P2 - CB DECLINE - LATEST PAYMENT DELINQUENT WITH OVERDUE BALANCE (WITH/WITHOUT CB RISK GRADE)"
'RG' = "RG - INTERNAL DECLINE - BEHAVIOR SCORE"
'RD' = "RD - INTERNAL DECLINE - BEHAVIOR SCORE TEST GROUP"
'N6' = "N6 - INTERNAL DECLINE - CC / CL OVERLIMIT (WITH OR WITHOUT CB RISK GRADE)"
'N7' = "N7 - INTERNAL DECLINE - CURRENT ACCOUNT WITH EXCESSES (WITH OR WITHOUT CB RISK GRADE)"
'N8' = "N8 - INTERNAL DECLINE - RETURNED CHEQUES (WITH OR WITHOUT CB RISK GRADE)"
'N9' = "N9 - INTERNAL DECLINE - CASH ADVANCE > 50% (WITH OR WITHOUT CB RISK GRADE)"
'N3' = "N3 - INTERNAL DECLINE (UNSECURED PRODUCTS) - PAYMENT HISTORY DELINQUENT WITH/WITHOUT CB RISK GRADE"
'N4' = "N4 - INTERNAL DECLINE (SECURED PRODUCTS) - PAYMENT HISTORY DELINQUENT WITH/WITHOUT CB RISK GRADE"
'N5' = "N5 - INTERNAL DECLINE (SECURED & UNSECURED) - PAYMENT HISTORY DELINQUENT WITH/WITHOUT CB RISK GRADE"
'P3' = "P3 - CB DECLINE (SECURED PRODUCTS) - PAYMENT HISTORY DELINQUENT" 
'P4' = "P4 - CB DECLINE (UNSECURED PRODUCTS) - PAYMENT HISTORY DELINQUENT"
'P5' = "P5 - CB DECLINE (SECURED & UNSECURED) - PAYMENT HISTORY DELINQUENT" 
'PV' = "PV - CB DECLINE - DELINQUENT PAYMENT HISTORY" 
'MO' = "MO - MINIMUM MONTHS ON BOOKS"
'NA' = "NA - FOREIGNER EMPLOYMENT PASS/NATIONALITY CHECKS"
'ME' = "ME - FAILED MUE POLICY"
'DV' = "DV - AUTO DECLINE ON PENDING CASES > X DAYS"
'RP' = "RP - FINANCING PERIOD > 60 MONTHS / FOREIGNER FINANCING PERIOD > 24 MONTHS"
'PH' = "PH - NO CONTACT NUMBER GIVEN"
'DO' = "DO - OTB < $500 DECLINE" 
'FQ' = "FQ - MIN PRODUCT LOAN / MIN LIMIT / FINANCING QUANTUM"
'DR' = "DR - RELATIONSHIP TO APPLICANT"
'SF' = "SF - STAFF INDICATOR"
'EF' = "EF - EMPLOYMENT CHECKS" 
'XF' = "XF - DECLINE-FOREIGNER BUREAU PREV INQUIRY"
'EX' = "EX - DECLINE-FOREIGNER CURR & PREV EMPLOYMENT"
'AF' = "AF - DECLINE-FAIL MIN INCOME OF $120K CUSTOMER" /* NEWLY ADDED FEB 2020 */


/*CODES USED BY SYS WEF 1SEP2010 (SYSTEM DECLINE GROUPS)*/
'NF' = "NF - INTERNAL DECLINE - LATEST NX DELINQ OR CURRENT V+ BLOCK CODES"
'BG' = "BG - CB DECLINE - RISK GRADE HZ OR HH OR SCORE < 1600"
'NB' = "NB - INTERNAL DECLINE - NX HISTORY & OTHERS"
'NH' = "NH - INTERNAL DECLINE - NX PAYMENT HISTORY"


/*CODES USED BY SYS WEF 1SEP2010 (SYSTEM REFER RSNS)*/
'IB' = "IB - REGULATORY REFER - BTI/60DPD NEGATIVE STATUS" /*EZ ADDED 30042015*/
'IQ' = "IQ - REGULATORY REFER - CUST HAS RAS (INT/EXT)" /*Collin ADDED 29062015*/
'IC' = "IC - REGULATORY REFER - BTI/60DPD LATEST BTI RATIO" /*EZ ADDED 30042015*/
'ID' = "ID - REGULATORY REFER - BTI/60DPD LITI/BANKRUPT IND" /*EZ ADDED 30042015*/
'IE' = "IE - REGULATORY REFER - BTI/60DPD PAYMENT HIST/BLK CODES" /*EZ ADDED 30042015*/
'IF' = "IF - REGULATORY REFER - BTI/60DPD LIMIT UTILIZATION" /*EZ ADDED 30042015*/
'IG' = "IG - REGULATORY REFER - BTI/60DPD BEHAVIORAL SCORE" /*EZ ADDED 30042015*/
'IH' = "IH - REGULATORY REFER - BTI/60DPD CB STATUS/RISK GRADE" /*EZ ADDED 30042015*/
'IJ' = "IJ - REGULATORY REFER - BTI/60DPD OTHERS" /*EZ ADDED 30042015*/
'UE' = "UE - REGULATORY REFER - 60DPD LATEST PAYT HIST/BLK CD" /*EZ ADDED 30042015*/
'UH' = "UH - REGULATORY REFER - 60DPD CB LATEST PAYT HIST/STA" /*EZ ADDED 30042015*/
'IM' = "IM - REGULATORY REFER - 60DPD SUSP FLAG" /*EZ ADDED 30042015*/
'IN' = "IN - REGULATORY REFER - BTI SUSP FLAG" /*EZ ADDED 30042015*/
'IO' = "BUREAU REFER - INDUSTRY UNSECURED LIMIT UTILIZATION" /*EZ ADDED 30042015*/
'IP' = "BUREAU REFER - CUSTOMER SECURED CREDIT LIMIT" /*EZ ADDED 30042015*/
'Q1' = "Q1 - INTERNAL REFER - NEGATIVE CUSTOMER STATUS"
'Q2' = "Q2 - INTERNAL REFER - ACCOUNT SIGNALS/RECALL DATE/JUDGEMENT DATE"
'Q3' = "Q3 - INTERNAL REFER - NX LATEST PAYMENT HISTORY"
'Q4' = "Q4 - INTERNAL REFER - CURRENT V+ BLOCK CODES"
'Q5' = "Q5 - INTERNAL REFER - DEFAULT RISK POOL" /*EZ ADDED 30042015*/

'Q6' = "Q6 - GOOD OR MARGINAL (BTI)/STRESSED"/*Collin added*/ /*Added Jul 17*/

'X1' = "X1 - CB REFER - BAD DEBT RECORD OR / DMP / LITI / BANKRUPT INDICATOR"
'X2' = "X2 - CB REFER - LATEST PAYMENT DELINQUENT" 
'X3' = "X3 - CB REFER - LATEST PAYMENT DELINQUENT WITH OVERDUE BALANCE (WITH OR WITHOUT CB RISK GRADE)"
'X4' = "X4 - CB REFER (SECURED PRODUCTS) - PAYMENT HISTORY"
'X5' = "X5 - CB REFER (UNSECURED PRODUCTS) - PAYMENT HISTORY"
'X6' = "X6 - CB REFER (SECURED & UNSECURED) - PAYMENT HISTORY"
'X7' = "X7 - CB REFER - NO. OF PREVIOUS INQUIRIES"
'X8' = "X8 - CB REFER - CB SCORE"
'RR' = "RR - CB REFER - CB RISK GRADE"
'YY' = "YY - INTERNAL REFER - BEHAVIOR SCORE"
'Y1' = "Y1 - INTERNAL REFER (UNSECURED PRODUCTS) - PAYMENT HISTORY DELINQUENT"
'Y2' = "Y2 - INTERNAL REFER (SECURED PRODUCTS) - PAYMENT HISTORY DELINQUENT"
'Y3' = "Y3 - INTERNAL REFER (UNSECURED & SECURED) - PAYMENT HISTORY DELINQUENT"
'Y4' = "Y4 - INTERNAL REFER - CC / CL OVERLIMIT"
'Y5' = "Y5 - INTERNAL REFER - CURRENT ACCOUNT EXCESS"
'Y6' = "Y6 - INTERNAL REFER - RETURNED CHEQUES"
'Y7' = "Y7 - INTERNAL REFER - CASH ADVANCE > 50%"
'YC' = "YC - INTERNAL REFER - CASH ADVANCE > 50% TEST GROUP"
'YA' = "YA - INTERNAL REFER - LITIGATION / BANKRUPT"
'YB' = "YB - INTERNAL REFER - AGE"
'YO' = "YO - INTERNAL REFER - MINIMUM MONTH ON BOOK (MOB)"
'M1' = "M1 - MUE>24X WITH RG=HX/GX/BX/CX OR EXCEED MUE IN GENERAL"
'M2' = "M2 - MUE>24X WITH RG=HH"
'M3' = "M3 - MUE>32X WITH RG=DD/EE/FF/GG"
'MC' = "MC - MUE>32X WITH RG=DD/EE/FF/GG TEST GROUP"
'M4' = "M4 - MUE>40X WITH RG=AA/BB/CC"
'MD' = "MD - MUE>40X WITH RG=AA/BB/CC TEST GROUP"
'M5' = "M5 - MUE NO FACILITY"
'Z1' = "Z1 - FOREIGNER>=120K, GREEN BUREAU MAX PDT LIMIT 20K"
'Z2' = "Z2 - FOREIGNER>=120K, MOB>=12MTHS, RG=AA/BB"
'Z3' = "Z3 - SG/SPR GREEN BUREAU MAX 4X"
'Z9' = "Z9 - GREEN BUREAU 4X AND MAX PRODUCT LIMIT 20K"
'Z5' = "Z5 - SG/SPR AI>=120K, GREEN BUREAU AND MAX AGG 20K"
'Z6' = "Z6 - SG/SPR AI>=120K WITH RISK GRADE"
'Z7' = "Z7 - SG/SPR AI>=120K, AAGG, FI<4"
'Z8' = "Z8 - SG/SPR AI>=120K, AAGG, FI>3"
'YT' = "YT - SELF-EMPLOYED-NON PROFESSIONAL<2YRS/1YR"
'S1' = "S1 - FAILED FINANCING QUANTUM OR EXCEED AGGREGATE LIMIT (SG)"
'F1' = "F1 - EXCEED AGGREGATE LIMIT"
'AR' = "AR - REFER - FAIL APPLICATION SCORE"
'V1' = "V1 - SYSTEM REFER FOR FOREINGER/DIPLOMAT > $XK"
'C1' = "C1 - INCOME REFER"
'YN' = "YN - INTERNAL REFER - MALE APPLICANT NOT ALLOWED FOR LADIES CARD"
'RO' = "RO - INTERNAL REFER - OTHERS"
'DU' = "DU - INTERNAL REFER - DUPLICATE APPLICATION / PRODUCT HOLDING"
'FV' = "FV - INTERNAL REFER - FAIL ON SUSPECT FRAUD"
'TR' = "TR - INTERNAL REFER - FAIL TERRORIST NAME CHECK"
'YR' = "YR - INTERNAL REFER - FOREIGNER RESIDING IN SINGAPORE / NATIONALITY"
'YS' = "YS - INTERNAL REFER - STATUTORY COMPLIANCE - STAFF APPLICATION"
'RA' = "RA - INTERNAL REFER - RELATIONSHIP TO APPLICANT"

'RB'  = "RB - REFER – DC SEGMENT"	/*Newly add Jan 17 */
'YM'  = "YM - REFER – LIMIT ASSIGNMENT"	/* Newly add Feb 20 */

/*MANUAL CODES USED BY CREDIT REVIEW WEF 1SEP2010*/
	/*APPROVAL CODE*/
/*
'E38' = "E38 - JOB STABILITY"
'E41' = "E41 - CUSTOMER PROFILE:LOCAL., HIGH INCOME EARNER &/OR, HIGH NETWORTH"
'E54' = "E54 - CUSTOMER PROFILE: FOREIGNER, ACCEPTABLE INCOME & EMPLOYMENT"
'E28' = "E28 - STATISFACTORY BUREAU RECORD"
'E58' = "E58 - NEW BORROWER TO BUREAU"
'E34' = "E34 - GOOD CONDUCT OF INTERNAL CREDIT FACILITIES"
'E55' = "E55 - CONDUCT OF ACCOUNT - DEPOSITORY"
'E56' = "E56 - STAFF APPLICATION"
'E60' = "E60 - PRIVATE BANKING"
'E46' = "E46 - FULLY SECURED"
*/
	/*APPROVAL CODES - DEVIATED CASES*/
/*
'X38' = "X38 - JOB STABILITY (DOA EXCEPTION)"
'X41' = "X41 - CUSTOMER PROFILE:LOCAL., HIGH INCOME EARNER &/OR, HIGH NETWORTH (DOA EXCEPTION)"
'X54' = "X54 - CUSTOMER PROFILE: FOREIGNER, ACCEPTABLE INCOME & EMPLOYMENT (DOA EXCEPTION)"
'X28' = "X28 - SATISFACTORY BUREAU RECORD (DOA EXCEPTION)"
'X58' = "X58 - NEW BORROWER TO BUREAU (DOA EXCEPTION)"
'X34' = "X34 - GOOD CONDUCT OF INTERNAL CREDIT FACILITIES (DOA EXCEPTION)"
'X55' = "X55 - CONDUCT OF ACCOUNT - DEPOSITORY (DOA EXCEPTION)"
'X56' = "X56 - STAFF APPLICATION (DOA EXCEPTION)"
'X60' = "X60 - PRIVATE BANKING (DOA EXCEPTION)"
'X46' = "X46 - FULLY SECURED (DOA EXCEPTION)"
*/


/*MANUAL CODES USED BY CREDIT REVIEW WEF 1SEP2016 :) */
	/*APPROVAL CODE*/
'E38' = "E38 - JOB STABILITY"
'E41' = "E41 - CUSTOMER PROFILE:LOCAL., HIGH INCOME EARNER &/OR, HIGH NETWORTH"
'E54' = "E54 - CUSTOMER PROFILE: FOREIGNER, ACCEPTABLE INCOME & EMPLOYMENT"
'E28' = "E28 - STATISFACTORY BUREAU RECORD"
'E58' = "E58 - NEW BORROWER TO BUREAU"
'E34' = "E34 - GOOD CONDUCT OF INTERNAL CREDIT FACILITIES"
'E55' = "E55 - CONDUCT OF ACCOUNT - DEPOSITORY"
'E56' = "E56 - STAFF APPLICATION"
'E60' = "E60 - PRIVATE BANKING"
'E46' = "E46 - FULLY SECURED"
'E11' = "E11 - APPLICATIONS WITHOUT EXCEPTIONS" /**newly added, we should be seeing this going forward**/

	/*APPROVAL CODES - DEVIATED CASES  WEF 1SEP2016 :) */
'X01' = "X01 - INTERNAL GUIDELINES(INTERNAL PAYMENT RECORDS/HISTORY,CIS,ETC)"
'X02' = "X02 - BUREAU PAYMENT HISTORY/RECORD/MUE RULE/RISK GRADE/LITIGATION(APPLY FOR RENO/FSA)"
'X03' = "X03 - AGE/RELATIONSHIP(<35(INSIGNIA) and >70(CARDS/CASHLINE)(RELATIONSHIP FOR FSA)"
'X04' = "X04 - OVERSEAS ADDRESSES"
'X05' = "X05 - 6 MONTH AUM <S$3M AND/OR AT POINT OF APPLICATION"
'X06' = "X06 - PROCESS EXCEPTION LIKE INSUFFICIENT INCOME DOCUMENT OR ANY OTHER OPERATING PROCESSES"

'X07' =	"X07 - BANKRUPTCY PETITION OR ORDER/DEBT REPAYMENT SCHEME OUTSTANDING"
'X08' =	"X08 - DISCHARGED BANKRUPT WITHIN THE LAST 12 MONTHS"
'X09' =	"X09 - FINANCIAL CONTRACT WITHIN THE LAST 12 MONTHS"
'X10' =	"X10 - FINANCIAL CONTRACT MORE THAN 12 MONTHS AGO"


	/*DECLINE CODES*/
'J62' = "J62 - HIGH RISK OCCUPATION"
'J03' = "J03 - JOB INSTABILITY"
'J19' = "J19 - EXCEED MUE CAP"
'J08' = "J08 - NEGATIVE BUREAU RECORD"
'J64' = "J64 - BUREAU RECORD WITH OVERDUE AMOUNT"
'J23' = "J23 - UNACCEPTABLE LITIGATION SUITS TRACED"
'J21' = "J21 - DISCHARGE BANKRUPT"
'J05' = "J05 - POOR INTERNAL REPAYMENT HISTORY"
'J55' = "J55 - NEGATIVE DEPOSIT ACCOUNT STATUS / TAGGING"
'J06' = "J06 - FAIL EMPLOYMENT CHECK - HARD TO LOCATE"
'J53' = "J53 - OVERLIMIT ON EXISTING CREDIT FACILITIES"
'J16' = "J16 - EXCEED DEBIT SERVICING RATIO (DBR)"
'J51' = "J51 - FAIL SCORE"
'J63' = "J63 - FAILED FURTHER LINE ASSIGNMENT"
'J15' = "J15 - SUSPECTED FRAUD"
'J04' = "J04 - BALANCE TO INCOME RATIO"
'J07' = "J07 - REPAYMENT ASSISTANCE SCHEME (RAS)" /*EZ ADDED ON 30042015*/

/*'OS'  = "OS - STRESSED SEGMENT" */											/*Newly add Jan 17 */
'OS'  = "OS - GOOD OR MARGINAL(BTI)/STRESSED" 	/*changed by collin on Jul*/	/*Newly add Jan 17 */

'B4'  = "B4 - FOREIGN CXGX AI<80K ADV IND"  		/*Newly add Jan 17 */
'NX'  = "NX - PORTFOLIO ACTION ON CLOSED ACCOUNT"	/*Newly add Jan 17 */

'OT'  = "INTERNAL DECLINE – BTI THRESHOLD"			/*Newly add Jan 17 */

/*CODES USED BY T&O CREDIT OPS WEF 1SEP2010*/
	/*CODES TO PROCEED*/
'A01' = "A01 - NO DEVIATION"
'A09' = "A09 - PASS CROSS CHECKS"

	/*DECLINE CODE*/
/*'J69' = "J69 - SELF-EMPLOYED <2YRS"*/
'J69' = "J69 - NOT MEET MINIMUM LENGTH OF EMPLOYMENT" /*changed by collin on Jul*/ /*changed to fit into PQR*/

'J70' = "J70 - DO NOT QUALITY FOR LOAN"
'RY' = "RY - NOT RESIDING LOCALLY/FAIL EMPLOYMENT CHECK"
'J14' = "J14 - BLACKLIST/CAUTION LIST - CREDIT RELATED"
'J65' = "J65 - BLACKLIST/CAUTION LIST  - FRAUD RELATED"
'J66' = "J66 - BLACKLIST/CAUTION LIST - OTHER"
'J01' = "J01 - INSUFFICIENT INCOME DOCS"
'J10' = "J10 - DOCUMENT DEFICIENCIES (FOR RENO LOAN)"
'DP' = "DP - INCOME DOES NOT MEET PRODUCT TARGET MARKET"
'J20' = "J20 - EXCEED 2X/4X INCOME"
'J25' = "J25 - FAILED LINE ASSIGNMENT"
'J26' = "J26 - LIST OF INSTITUTIONS NOT IN FSA APPROVED LIST"
'J27' = "J27 - CM HAS EXISTING CASHLINE/POSB LA ACCT"
'J28' = "J28 - RENOVATION CONTRACTOR LIST NOT IN HDB LISTING"
'J54' = "J54 - CIS TAGGED WITH TERRORIST STATUS"
'J60' = "J60 - INSUFFICIENT OTB"
'J68' = "J68 - NO RESPONSE TO OFFER BASED ON RISK PRICING"
'J67' = "J67 - EXISTING UNSECURED FAC APPLY FOR MAC"
'J61' = "J61 - POOR BANK CONDUCT"

'J24' = "J24 - DCP WITH OTHER BANKS < 90 DAYS" /*changed by collin on Jul*/

	/* Cancellation Code */
'W01' = 	"W01 - Prefer other bank's Loan Amt"
'W02' = 	"W02 - Prefer other bank's Loan tenor"
'W03' = 	"W03 - Prefer other bank's Cash Bonus"
'W04' = 	"W04 - Prefer other bank's Other bonus"
'W05' = 	"W05 - Prefer other bank's Repayment method"
'W06' = 	"W06 - Prefer other bank's Penalty Clause"
'W07' = 	"W07 - Prefer other bank's Faster turnaround time"
'W08' = 	"W08 - Prefer other bank's Penalty charged"
'W09' = 	"W09 - Prefer other bank's Better rate"
'W10' = 	"W10 - Prefer other bank's existing banker"
'W11' = 	'W11 - Poor service manner'
'W12' = 	'W12 - Execute too much documents'
'W13' = 	'W13 - Slow approval turnaround time'
'W14' = 	'W14 - Branch not easy accessed'
'W15' = 	'W15 - Slow charge instruction'
'W16' = 	'W16 - Long loan disbursement time'
'W17' = 	'W17 - Inflexible loan repayment method'
'W18' = 	'W18 - Unwilling/unable to provide further info'
'W19' = 	'W19 - Unwilling to document verification/fulfilment'
'W20' = 	'W20 - Prefer other products to be offered by our bank'
'W21' = 	'W21 - Inflexible to open deposit accts at designated branch'
'W22' = 	'W22 - Non-residential mortgage'
'W23' = 	'W23 - Duplicate application'
'W24' = 	'W24 - No such need'
'W25' = 	'W25 - No response'
'W26' = 	'W26 - No reason given'
'W27' = 	"W27 - Prefer Developer's finance company"
'W28' = 	'W28 - Offer amount less than requested'
'W29' = 	'W29 - Does not meet policy requirement'
'W30' = 	'W30 - No application form'
'W31' = 	'W31 - Expired Application Form (Cards)'
'W32' = 	'W32 - Outsourcer Data Entry Error'
'W70' = 	'W70 - Approved but account not created in Cardlink'
'W99' = 	'W99 - Others '

	/* Codes added by GCC MIS to classify groupings */
'T01' = 'Pre-Val - 2xIncome < Credit Desired'
'T02' = 'Pre-Val - Credit Desired > Payment Amt'
'T03' = 'Pre-Val - Fail DSR'
'T04' = 'Cancelled at Judgement'
'T05' = 'Cancelled at verification'
'T06' = 'Cancelled at Edit'
'T07','XX' = 'Score declined'

/* Codes added by IVAN for BANKING BEHAVIOUR */
'E12' = 'E12 - APPROVE UNDER BANKING BEHAVIOUR TEST PROGRAM'
'J12' = 'J12 - NOT IN BANKING BEHAVIOUR TEST PROGRAM'
'AC' = 'FAIL ASCORE'
;

value $Cat
'S0a' = 'SYS Approve'
'S0d' = 'SYS Decline'
'S0c' = 'SYS Cancel'
'S0r' = 'SYS Refer'

'S1' = 'SYS Regulatory'
'S2' = 'SYS Negative Internal Check'
'S3' = 'SYS Negative External Check'
'S4' = 'SYS Internal Policy '
'S5' = 'SYS Suspected Fraud'
'S6' = 'SYS Failed Technical Verification'
'S7' = 'SYS Product'
'S9' = 'SYS Positive Check'

'C0' = 'CR Unknown'
'C1' = 'CR Pos Applicant Profile'
'C2' = 'CR Pos External Checks'
'C3' = 'CR Pos Internal Checks'
'C4' = 'CR Pos Special Arrangement'
'C5' = 'CR Neg Applicant Profile'
'C6' = 'CR Neg MUE'
'C7' = 'CR Neg External Checks'
'C8' = 'CR Neg Internal Checks'

'O1' = 'T&O Proceed'
'O2' = 'T&O Neg Applicant Profile'
'O3' = 'T&O Neg Caution List'
'O4' = 'T&O Neg Data Verification'
'O5' = 'T&O Neg Internal Checks'
'O6' = 'T&O Cancel'
;


value $Stage
'ED'='A. EDIT'
'DV'='B. DATA VERIFICATION'
'CC'='C. CROSS CHECK'
'PV'='D. PRE-VALIDATION'
'CB'='Credit Bureau'
'AS'='E. APPLICATION SCORE'
'JD'='F. FINAL JUDGEMENT';

VALUE $CDTYPE
'250' = "250 - NEW-MAC MICRO $500 LINE"
'260' = "260 - $500 LIMIT CREDIT CARD - LIVEFRESH"
'300' = "300 - CREDIT CARD - MASS MARKET"
'301' = "301 - CREDIT CARD - SUPPLEMENTARY"
'303' = "303 - CREDIT CARD - EXISTING VIP ADD ON CARD"
'304' = "304 - DBS SECURED CARDS"
'305' = "305 - CREDIT CARD - STAFF"
'306' = "306 - CREDIT CARD - VIP"
'309' = "309 - CREDIT - EXISTING MASS MKT ADD ON CARD"
'311' = "311 - PERM LINE INCREASE"
'312' = "312 - CARDS BALANCE TRANSFER"
'314' = "314 - SECURED CARD PERM INCREASE"
'316' = "316 - CREDIT CARD - INSTALLMENT LOAN (IPP)"
'321' = "321 - CREDIT CARD - LINE REDUCTION"
'330' = "330 - CORPORATE CREDIT CARD"
'331' = "331 - CORPORATE CREDIT CARD - JOINT AND SEVERAL LIABILITY"
'332' = "332 - CORPORATE VIRTUAL CARD"
'333' = "333 - CREDIT CARD - LINE SWITCH FOR SPOREAN"
'377' = "377 - PERM INCREASE $120K (DM)"
'388' = "388 - CREDIT CARD - SUPER PREMIUM"
'399' = "399 - SUPER PREMIUM PERM INCREASE"
'520' = "520 - DBS TREASURES VISA INFINITE"
'521' = "521 - DBSI - FOLLOW UP SUPP"
'522' = "522 - DBSI - PERM LINE INCREASE"
'900' = "900 - ANNUAL REVIEW OF CARD WITH CREDIT LIMIT >=$300"
'050' = "050 - PROACTIVE REINSTATEMENT"
'040' = "040 - REACTIVE REINSTATEMENT"

'523' = "523 - DBS TREASURES VISA INFINITE"
'200' = "200 - MAC WITH 4X INCOME LINE NAD SCORE"
'209' = "209 - ADD-ON MAC WITH 4X INCOME LINE" 
'334' = "334 - PERM LINE INCREASE J&S" /* Collin added Apr 2016 */

'371' = "371 - SURVIVAL CREDIT" /* Newly added Jun 18 */
'158' = "158 - $120K CUSTOMER" /* Newly added Feb 20 */

;

VALUE $CLTYPE
'410' = "410 - CASHLINE"
'411' = "411 - CASHLINE IPP (WEF OCT09)"
'412' = "412 - CASHLINE BT/FT"
'416' = "416 - CR ASSIST CONVERSION"
'417' = "417 - AIP INTERNET/ATM"
'418' = "418 - CASHLINE INSTALMENT LOAN (WEF OCT08)"
'419' = "419 - CASHLINE COMPLIMENTARY (WEF FEB09)"
'420' = "420 - CASHLINE - IPP COMPLIMENTARY (WEF JUN10)"
'428' = "428 - STAFF"
'433' = "433 - 16% BANK INITIATE"
'438' = "438 - COMPLIMENTARY"
'444' = "444 - CASHLINE LINE SWITCH FOR SPRN (WEF JUN10)"
'450' = "450 - PERMLINE"
'451' = "451 - CASHLINE - LINE REDUCTION"
'452' = "452 - PERM LINE INCREASE"

'460' = "460 - PAYDOWN ASSISTANCE"
'469' = "469 - POSB LOAN ASSIST (SECOND LOAN)"

'470' = "470 - REPAYMENT ASSISTANCE SCHEME" /*EZ ADDED 30042015*/

'480' = "480 - CASHLINE<$30K (CR OPS)"
'481' = "481 - CASHLINE<$30K (BRANCHES)"

'482' = "482 - CASHLINE ELITE (BRANCHES)"

'483' = "483 - CASHLINE<$30K-STAFF"

'490' = "490 - POSB LA PLUS - BRANCHES"
'491' = "491 - POSB LA PLUS (BRANCHES)"

'492' = "492 - POSB LA ELITE (BRANCHES)" 

'466' = "466 - TOTEBOARD MICRO LOAN"
'465' = "465 - PARKWAY MEDICAL LOAN"
'850' = "850 - MARGIN TRADING"

'100' = "100 - DBS MYRENO"
'108' = "108 - STAFF RENOVATION LOAN"
'110' = "110 - POSB RENOVATION LOAN"
'307' = "307 - NOT IN USE"
'314' = "314 - <BLANK>"
'500' = "500 - DBS CREDIT ASSIST/CARD"
'600' = "600 - DBS FURTHER STUDY ASSIST I"
'650' = "650 - POSB FURTHER STUDY ASSIST"
'800' = "800 - DBS STUDENT ASSIST"
'901' = "901 - CARDS BALANCE TRANSFER"
'902' = "902 - CARDS"
'903' = "903 - SMART CASH"
'911' = "911 - CARDS BALANCE TRANSFER"
'912' = "912 - CREDIT CARDS"
'913' = "913 - CASHLINE"
'914' = "914 - RENO LOAN"

'710'	  ="710-UNIVERSITY TFL/SL/CL"
'720'	  ="720-SMU TFL/SL/CL"
'730'	  ="730-POLYTECHNICS TFL/SL/CL"
'740'	  ="740-FSI"
'750'	  ="750-GUARANTOR CHANGE"
'414'	  ="414-CASHLINE PLUS & INSTL LOAN" /*newly added Jan17*/
'413'	  ="413-CASHLINE & INSTL LOAN"		/*newly added Jan17*/

'471'	  ="471-DEBT CONSOLIDATION LOAN"	/*newly added DC Jan17*/
;




VALUE $CAMPAIGNA /*CR=DIRECT SALES WEF 2014*/
/*EZ UPDATE ON 30032015*/
'EM', 'SC', 'SN', 'SY'							= "01. ONLINE"
'TA', 'TM', 'TR'									= "02. TELEMARKETING"
'EB', 'OB', 'OX', 'OZ', 'OS', 'OV', 'OU'		= "03. BRANCH"
'DM'													= "04. DIRECT MAILER"
'OA', 'OP', 'OR'									= "05. TAKE ONES"
'SD'													= "06. ATM"
'AS', 'AW', 'FE'									= "07. INSERTS"
'MB' 													= "08. MOBILE APPS"
'CR', 'DS', 'ER', 'SH', 'TH', 'TS'				= "09. DIRECT SALES" 
'TC'													= "10. CONTACT CENTRE"
'ST'													= "11. STAFF"
'GM', 'OT', 'UA', 'ZT'							= "12. OTHERS"
OTHER												= "13. NOT ASSIGNED";

VALUE $CAMPAIGNO /*CR=ROADSHOWS BEFORE 2014*/
/*EZ UPDATE ON 30032015*/
'EM', 'SC', 'SN', 'SY'							= "01. ONLINE"
'TA', 'TM', 'TR'									= "02. TELEMARKETING"
'EB', 'OB', 'OX', 'OZ', 'OS', 'OV', 'OU'		= "03. BRANCH"
'DM'													= "04. DIRECT MAILER"
'OA', 'OP', 'OR'									= "05. TAKE ONES"
'SD'													= "06. ATM"
'AS', 'AW', 'FE'									= "07. INSERTS"
'MB' 													= "08. MOBILE APPS"
'DS', 'ER', 'SH', 'TH', 'TS'						= "09. DIRECT SALES" 
'TC'													= "10. CONTACT CENTRE"
'ST'													= "11. STAFF"
'GM', 'OT', 'UA', 'ZT'							= "12. OTHERS"
'CR'													= "13. ROADSHOWS"
OTHER												= "14. NOT ASSIGNED";

VALUE $RG
'AA'	= "01. AA"
'BB'	= "02. BB"
'CC'	= "03. CC"
'DD'	= "04. DD"
'EE'	= "05. EE"
'FF'	= "06. FF"
'GG'	= "07. GG"
'HH'	= "08. HH"
'HZ'	= "09. HZ"
'BX' 	= "10. BX"
'CX'	= "11. CX"
'GX' 	= "12. GX"
'HX'	= "13. HX"
OTHER = "14. OTHERS";

VALUE $EMPLOYTERMX
'E'		= "01. EMPLOYED"
'S'		= "02. SELF-EMPLOYED"
'C'		= "03. COMMISSION EARNER"
'O'		= "04. OTHERS"
'M'		= "05. MISSING";

VALUE $EDUC
'01'	= "PHD/DOCTORATE"
'02'	= "MASTERS"
'03'	= "DEGREE"
'04'	= "PROFESSIONAL"
'05'	= "DIPLOMA"
'06'	= "TECHNICAL"
'07' 	= "A LEVEL"
'08'	= "SECONDARY"
'09'	= "PRIMARY"
'10'	= "OTHERS"
'11'	= "NO RESPONSE"
OTHER = "UNKNOWN";

VALUE $POSITION
'01', '19', '06', '07', '09', '20', '28', '29', '30' 		= "1. SENIOR MGMT, SUPERVISOR, SKILLED"
'03', '04', '05', '14', '15', '16', '17', '18', '25'		= "2. MIDDLE MGMT, CLERICAL"
'11', '12', '13'													= "3. DIRECTOR"
'02', '22', '23', '24', '26', '27'							= "4. PROFESSIONAL"
OTHER, '10'													= "5. OTHERS"
'08' 																= "6. NO RESPONSE"
;

VALUE SCORE
LOW-303 		= "A. RJ: 303 AND BELOW"
304-319 		= "B. AP: 304-319"
320-344 		= "C. AP: 320-344"
345-400 		= "D. AP: 345-400"
401-HIGH 		= "E. AP: 401 AND ABOVE";

VALUE CLSCORE
LOW-294		= "A. RJ: 294 AND BELOW"
295-331		= "B. AP: 295-331"
332-372		= "C. AP: 332-372"
373-392		= "D. AP: 373-392"
393-HIGH		= "E. AP: 393 AND ABOVE";

VALUE CCNTBSCORE
LOW-319 		= "A. RJ: 319 AND BELOW"
320-323 		= "B. REFER: 320-323"
324-351		= "C. AP: 324-351"
352-390		= "D. AP: 352-390"
391-407		= "E. AP: 391-407"
408-HIGH		= "F. AP: 408 AND ABOVE";

VALUE CCEXBSCORE
LOW-250		= "A. 250 AND BELOW"
251-259		= "B. REFER: 251-259"
260-296		= "C. AP: 260-296"
297-333		= "D. AP: 297-333"
334-375		= "E. AP:334-375"
376-421		= "F. AP: 376-421"
422-455		= "G. AP: 422-455"
456-HIGH		= "H. AP: 456 AND ABOVE";

VALUE CLNTBSCORE
LOW-319		= "A. RJ: 319 AND BELOW"
320-323		= "B. REFER: 320-323"
324-342		= "C. AP: 324-342"
343-371		= "D. AP: 343-371"
372-HIGH		= "E. AP: 372 AND ABOVE";

VALUE CLEXBSCORE
LOW-164		= "A. RJ: 164 AND BELOW"
165-194		= "B. REFER: 165-194"
195-275		= "C. AP: 195-275"
276-341		= "D. AP: 276-341"
342-369		= "E. AP: 342-369"
370-HIGH		= "F. AP: 370 AND ABOVE";

VALUE LANTBSCORE
LOW-251		= "A. RJ: 251 AND BELOW"
252-265		= "B. REFER: 252-265"
266-271		= "C. AP: 266-271"
272-302		= "D. AP: 272-302"
303-315		= "E. AP: 303-315"
316-HIGH		= "F. AP: 316 AND ABOVE";

VALUE LAEXBSCORE
LOW-164		= "A. RJ: 164 AND BELOW"
165-194		= "B. REFER: 165-194"
195-257		= "C. AP: 195-257"
258-312		= "D. AP: 258-312"
313-HIGH		= "E. AP: 313 AND ABOVE";


RUN;




************************************************************************************
	PRIORITY CHANGES FROM 15 JAN 2015	
	DECLINE CODE EXPANSION FROM 99 TO 249 FROM SEP 2014. 
	DO NOT READ FOR AMRL_DECLINE_REASON_249 AS IT WILL HOLD INFO SUCH AS 'FS'
	CHANGES: DECLINE (FROM 1-100) REFER (FROM 101-248) OTHER (249)
*************************************************************************************;

%MACRO Q_SYSRSN;
	%DO I = 248 %TO 101 %BY -1;
	LENGTH WHATREASON FIN_REASON $3. /*CATEGORY $32. RSN_OPER $3.*/;
	IF AMRL_DECLINE_REASON_&I NOT IN ('') THEN DO; FIN_REASON=AMRL_DECLINE_REASON_&I; /*CATEGORY='S0R';*/ END;
	%END;
	%DO U = 100 %TO 1 %BY -1;
	IF AMRL_DECLINE_REASON_&U NOT IN ('') THEN DO; FIN_REASON=AMRL_DECLINE_REASON_&U; /*CATEGORY='S0D';*/ END;
	%END;
	WHATREASON=FIN_REASON;
	 /*RSN_OPER='SYS';*/
%MEND Q_SYSRSN;


%MACRO N_RULEFAIL;

LENGTH RULEFAIL_LIST $80.;
%DO I=248 %TO 1 %BY -1;
IF AMRL_DECLINE_REASON_&I NOT IN ('') THEN DO;

RULEFAIL_LIST=(catx(',', of RULEFAIL_LIST, of AMRL_DECLINE_REASON_&I));

END;
%END;

%MEND N_RULEFAIL;


/* CATER FOR TOP REFERRAL REASON - 14 APR 2020 */
/*
%MACRO O_REFRSN;
     %DO I = 98 %TO 50 %BY -1;
     LENGTH RSNGRP_REF $3. ;
     IF AMRL_DECLINE_REASON_&I NOT IN ('') THEN DO; RSNGRP_REF=AMRL_DECLINE_REASON_&I; END;
     %END;
%MEND O_REFRSN;

%MACRO N_REFRSN;
     %DO I = 248 %TO 101 %BY -1;
     LENGTH RSNGRP_REF $3. ;
     IF AMRL_DECLINE_REASON_&I NOT IN ('') THEN DO; RSNGRP_REF=AMRL_DECLINE_REASON_&I; END;
     %END;
%MEND N_REFRSN;
*/

data temp_CDM_ALL_1;
set ds_uat./*mth*/cardscdm&yymm(keep=
ORG
TYPE
APPLICATION
AMRL_NBR_OF_ASSOCS
AMRL_STATUS
AMRL_LAST_MAINT
AMRL_LAST_MAINT_OPER
AMRL_ACCEPT_DECLINE_IND
AMRL_DECISION_DATE
AMRL_DECISION_OPER
AMRL_DATE_ENTERED_EDIT
AMRL_DATE_EXITED_EDIT
AMRL_EDIT_OPER
AMRL_EDIT_STATUS
AMRL_PRE_VAL_OPER
AMRL_PRE_VAL_STATUS
AMRL_PRE_VAL_RESULT
AMRL_APP_SCORE_RESULT
AMRL_VERFICATION_OPER
AMRL_VERFICATION_STATUS
AMRL_VERFICATION_RESULT
AMRL_JUDGEMENT_OPER
AMRL_JUDGEMENT_STATUS
AMRL_JUDGEMENT_RESULT
AMRL_SETUP_OPER
AMRL_SETUP_STATUS
AMRL_DECLINE_REASON_44
AMRL_FULL_NAME_1
AMRL_COUNTRY_1
AMRL_DRIVER_LICENSE_NBR_1
AMRL_USER_FIELD_ALPHA_1_1_3
AMRL_USER_FIELD_ALPHA_10_1_5
AMRL_USER_FIELD_ALPHA_3_1_2
AMRL_USER_FIELD_ALPHA_3_1_4
AMRL_USER_FIELD_ALPHA_5_1_2
SMRL_USER_FIELD_ALPHA_23_1_19

AMRL_DECLINE_REASON_1
AMRL_DECLINE_REASON_2
AMRL_DECLINE_REASON_3
AMRL_DECLINE_REASON_4
AMRL_DECLINE_REASON_5
AMRL_DECLINE_REASON_6
AMRL_DECLINE_REASON_7
AMRL_DECLINE_REASON_8
AMRL_DECLINE_REASON_9
AMRL_DECLINE_REASON_10
AMRL_DECLINE_REASON_11
AMRL_DECLINE_REASON_12
AMRL_DECLINE_REASON_13
AMRL_DECLINE_REASON_14
AMRL_DECLINE_REASON_15
AMRL_DECLINE_REASON_16
AMRL_DECLINE_REASON_17
AMRL_DECLINE_REASON_18
AMRL_DECLINE_REASON_19
AMRL_DECLINE_REASON_20
AMRL_DECLINE_REASON_21
AMRL_DECLINE_REASON_22
AMRL_DECLINE_REASON_23
AMRL_DECLINE_REASON_24
AMRL_DECLINE_REASON_25
AMRL_DECLINE_REASON_26
AMRL_DECLINE_REASON_27
AMRL_DECLINE_REASON_28
AMRL_DECLINE_REASON_29
AMRL_DECLINE_REASON_30
AMRL_DECLINE_REASON_31
AMRL_DECLINE_REASON_32
AMRL_DECLINE_REASON_33
AMRL_DECLINE_REASON_34
AMRL_DECLINE_REASON_35
AMRL_DECLINE_REASON_36
AMRL_DECLINE_REASON_37
AMRL_DECLINE_REASON_38
AMRL_DECLINE_REASON_39
AMRL_DECLINE_REASON_40
AMRL_DECLINE_REASON_41
AMRL_DECLINE_REASON_42
AMRL_DECLINE_REASON_43
AMRL_DECLINE_REASON_44
AMRL_DECLINE_REASON_45
AMRL_DECLINE_REASON_46
AMRL_DECLINE_REASON_47
AMRL_DECLINE_REASON_48
AMRL_DECLINE_REASON_49
AMRL_DECLINE_REASON_50
AMRL_DECLINE_REASON_51
AMRL_DECLINE_REASON_52
AMRL_DECLINE_REASON_53
AMRL_DECLINE_REASON_54
AMRL_DECLINE_REASON_55
AMRL_DECLINE_REASON_56
AMRL_DECLINE_REASON_57
AMRL_DECLINE_REASON_58
AMRL_DECLINE_REASON_59
AMRL_DECLINE_REASON_60
AMRL_DECLINE_REASON_61
AMRL_DECLINE_REASON_62
AMRL_DECLINE_REASON_63
AMRL_DECLINE_REASON_64
AMRL_DECLINE_REASON_65
AMRL_DECLINE_REASON_66
AMRL_DECLINE_REASON_67
AMRL_DECLINE_REASON_68
AMRL_DECLINE_REASON_69
AMRL_DECLINE_REASON_70
AMRL_DECLINE_REASON_71
AMRL_DECLINE_REASON_72
AMRL_DECLINE_REASON_73
AMRL_DECLINE_REASON_74
AMRL_DECLINE_REASON_75
AMRL_DECLINE_REASON_76
AMRL_DECLINE_REASON_77
AMRL_DECLINE_REASON_78
AMRL_DECLINE_REASON_79
AMRL_DECLINE_REASON_80
AMRL_DECLINE_REASON_81
AMRL_DECLINE_REASON_82
AMRL_DECLINE_REASON_83
AMRL_DECLINE_REASON_84
AMRL_DECLINE_REASON_85
AMRL_DECLINE_REASON_86
AMRL_DECLINE_REASON_87
AMRL_DECLINE_REASON_88
AMRL_DECLINE_REASON_89
AMRL_DECLINE_REASON_90
AMRL_DECLINE_REASON_91
AMRL_DECLINE_REASON_92
AMRL_DECLINE_REASON_93
AMRL_DECLINE_REASON_94
AMRL_DECLINE_REASON_95
AMRL_DECLINE_REASON_96
AMRL_DECLINE_REASON_97
AMRL_DECLINE_REASON_98
AMRL_DECLINE_REASON_99
AMRL_DECLINE_REASON_100
AMRL_DECLINE_REASON_101
AMRL_DECLINE_REASON_102
AMRL_DECLINE_REASON_103
AMRL_DECLINE_REASON_104
AMRL_DECLINE_REASON_105
AMRL_DECLINE_REASON_106
AMRL_DECLINE_REASON_107
AMRL_DECLINE_REASON_108
AMRL_DECLINE_REASON_109
AMRL_DECLINE_REASON_110
AMRL_DECLINE_REASON_111
AMRL_DECLINE_REASON_112
AMRL_DECLINE_REASON_113
AMRL_DECLINE_REASON_114
AMRL_DECLINE_REASON_115
AMRL_DECLINE_REASON_116
AMRL_DECLINE_REASON_117
AMRL_DECLINE_REASON_118
AMRL_DECLINE_REASON_119
AMRL_DECLINE_REASON_120
AMRL_DECLINE_REASON_121
AMRL_DECLINE_REASON_122
AMRL_DECLINE_REASON_123
AMRL_DECLINE_REASON_124
AMRL_DECLINE_REASON_125
AMRL_DECLINE_REASON_126
AMRL_DECLINE_REASON_127
AMRL_DECLINE_REASON_128
AMRL_DECLINE_REASON_129
AMRL_DECLINE_REASON_130
AMRL_DECLINE_REASON_131
AMRL_DECLINE_REASON_132
AMRL_DECLINE_REASON_133
AMRL_DECLINE_REASON_134
AMRL_DECLINE_REASON_135
AMRL_DECLINE_REASON_136
AMRL_DECLINE_REASON_137
AMRL_DECLINE_REASON_138
AMRL_DECLINE_REASON_139
AMRL_DECLINE_REASON_140
AMRL_DECLINE_REASON_141
AMRL_DECLINE_REASON_142
AMRL_DECLINE_REASON_143
AMRL_DECLINE_REASON_144
AMRL_DECLINE_REASON_145
AMRL_DECLINE_REASON_146
AMRL_DECLINE_REASON_147
AMRL_DECLINE_REASON_148
AMRL_DECLINE_REASON_149
AMRL_DECLINE_REASON_150
AMRL_DECLINE_REASON_151
AMRL_DECLINE_REASON_152
AMRL_DECLINE_REASON_153
AMRL_DECLINE_REASON_154
AMRL_DECLINE_REASON_155
AMRL_DECLINE_REASON_156
AMRL_DECLINE_REASON_157
AMRL_DECLINE_REASON_158
AMRL_DECLINE_REASON_159
AMRL_DECLINE_REASON_160
AMRL_DECLINE_REASON_161
AMRL_DECLINE_REASON_162
AMRL_DECLINE_REASON_163
AMRL_DECLINE_REASON_164
AMRL_DECLINE_REASON_165
AMRL_DECLINE_REASON_166
AMRL_DECLINE_REASON_167
AMRL_DECLINE_REASON_168
AMRL_DECLINE_REASON_169
AMRL_DECLINE_REASON_170
AMRL_DECLINE_REASON_171
AMRL_DECLINE_REASON_172
AMRL_DECLINE_REASON_173
AMRL_DECLINE_REASON_174
AMRL_DECLINE_REASON_175
AMRL_DECLINE_REASON_176
AMRL_DECLINE_REASON_177
AMRL_DECLINE_REASON_178
AMRL_DECLINE_REASON_179
AMRL_DECLINE_REASON_180
AMRL_DECLINE_REASON_181
AMRL_DECLINE_REASON_182
AMRL_DECLINE_REASON_183
AMRL_DECLINE_REASON_184
AMRL_DECLINE_REASON_185
AMRL_DECLINE_REASON_186
AMRL_DECLINE_REASON_187
AMRL_DECLINE_REASON_188
AMRL_DECLINE_REASON_189
AMRL_DECLINE_REASON_190
AMRL_DECLINE_REASON_191
AMRL_DECLINE_REASON_192
AMRL_DECLINE_REASON_193
AMRL_DECLINE_REASON_194
AMRL_DECLINE_REASON_195
AMRL_DECLINE_REASON_196
AMRL_DECLINE_REASON_197
AMRL_DECLINE_REASON_198
AMRL_DECLINE_REASON_199
AMRL_DECLINE_REASON_200
AMRL_DECLINE_REASON_201
AMRL_DECLINE_REASON_202
AMRL_DECLINE_REASON_203
AMRL_DECLINE_REASON_204
AMRL_DECLINE_REASON_205
AMRL_DECLINE_REASON_206
AMRL_DECLINE_REASON_207
AMRL_DECLINE_REASON_208
AMRL_DECLINE_REASON_209
AMRL_DECLINE_REASON_210
AMRL_DECLINE_REASON_211
AMRL_DECLINE_REASON_212
AMRL_DECLINE_REASON_213
AMRL_DECLINE_REASON_214
AMRL_DECLINE_REASON_215
AMRL_DECLINE_REASON_216
AMRL_DECLINE_REASON_217
AMRL_DECLINE_REASON_218
AMRL_DECLINE_REASON_219
AMRL_DECLINE_REASON_220
AMRL_DECLINE_REASON_221
AMRL_DECLINE_REASON_222
AMRL_DECLINE_REASON_223
AMRL_DECLINE_REASON_224
AMRL_DECLINE_REASON_225
AMRL_DECLINE_REASON_226
AMRL_DECLINE_REASON_227
AMRL_DECLINE_REASON_228
AMRL_DECLINE_REASON_229
AMRL_DECLINE_REASON_230
AMRL_DECLINE_REASON_231
AMRL_DECLINE_REASON_232
AMRL_DECLINE_REASON_233
AMRL_DECLINE_REASON_234
AMRL_DECLINE_REASON_235
AMRL_DECLINE_REASON_236
AMRL_DECLINE_REASON_237
AMRL_DECLINE_REASON_238
AMRL_DECLINE_REASON_239
AMRL_DECLINE_REASON_240
AMRL_DECLINE_REASON_241
AMRL_DECLINE_REASON_242
AMRL_DECLINE_REASON_243
AMRL_DECLINE_REASON_244
AMRL_DECLINE_REASON_245
AMRL_DECLINE_REASON_246
AMRL_DECLINE_REASON_247
AMRL_DECLINE_REASON_248
AMRL_DECLINE_REASON_249

AMRL_CREDIT_LIMIT

);

where AMRL_DECISION_DATE ge &setStartDT;

proc sort tagsort data=temp_CDM_ALL_1 out=temp_CDM_ALL_1_2; 
by APPLICATION AMRL_DECISION_DATE;
run;

DATA temp_CDM_ALL_2;
	SET temp_CDM_ALL_1;
	WHERE ORG IN ('702');

	IF MONTH(AMRL_DECISION_DATE)ge &MMM AND YEAR(AMRL_DECISION_DATE)ge &YYYY;

/**************REQUEST FOR APPROVAL TO CORRECT APPROVAL CODE ERROR; DC Deviation Rate booked in Jan & Feb 2020.**************/

	IF APPLICATION IN 
	(
	'2019364165913',
	'2019364090839',
	'2020014134242',
	'2020015154229',
	'2020020153257',
	'2020015124529',
	'2020021134706',
	'2020023165155',
	'2020028153657',
	'2020023100754',
	'2020028134425',
	'2020028163657',
	'2020030150410',
	'2020030172714',
	'2020036112953',
	'2020037151357',
	'2020037181215',
	'2020041112450',
	'2020041172008',
	'2020044105106',
	'2020050133222',
	'2020050143048',
	'2020056095006',
	'2020057093429'
	) 
	THEN DO;	
	AMRL_USER_FIELD_ALPHA_3_1_4 = 'E11';
	END;


	LENGTH PDT $10.; PDT="CARD";
	FORMAT PROCESS PROCESS_GRP $20.;

	IF TYPE IN ('260', '300', '306') THEN 												PROCESS = "1. NEW APPLICATION";
	ELSE IF TYPE IN ('303', '307', '308', '309') THEN 									PROCESS = "2. ADD-ON";
	ELSE IF TYPE IN ('304', '305')	THEN												PROCESS = "3. SECURED & STAFF";
	ELSE IF TYPE IN ('301', '340', '341', '700') THEN									PROCESS = "4. OTHERS";
	ELSE IF TYPE IN ('311', '313', '314', '321', '333', '399', '377','334', '378') THEN 		PROCESS = "5. LINE MGT"; /*Collin added 334 on Apr 2016*/ /*Kelvin added 378 on May 2020*/
	ELSE IF TYPE IN ('312') THEN														PROCESS = "6. BT/FT";
	ELSE IF TYPE IN ('330', '331', '332') THEN											PROCESS = "7. CORPORATE";
	ELSE IF TYPE IN ('520', '521', '522', '523') THEN									PROCESS = "8. AUM CARD";
	ELSE IF TYPE IN ('316') THEN														PROCESS = "9. INSTALMENT LOAN";
	ELSE IF TYPE IN ('200', '209', '250') THEN											PROCESS = "10. MAC"; 
	ELSE IF TYPE IN ('388') THEN 														PROCESS = "11. SUPER PREMIUM";
	ELSE IF TYPE IN ('900') THEN 														PROCESS = "12. REVIEW PORTFOLIO";
	ELSE IF TYPE IN ('040','050') THEN 													PROCESS = "13. REINSTATEMENT";
	ELSE 																				PROCESS = "13. NOT-ASSIGNED"; 

	IF TYPE IN ('260','300','306') THEN													PROCESS_GRP="1. NEW APPLICATION";
	ELSE																				PROCESS_GRP="2. PORTFOLIO ACTION";

	LENGTH WHATREASON $3.;
	
	/* DEFINE ACCEPTED APPLICATIONS */
	IF AMRL_ACCEPT_DECLINE_IND = "A" THEN DO;
		IF AMRL_USER_FIELD_ALPHA_3_1_4 NE ' ' THEN WHATREASON = AMRL_USER_FIELD_ALPHA_3_1_4;
	END;

LENGTH REJECTIND$2.;

IF AMRL_ACCEPT_DECLINE_IND='D' THEN DO;
	IF AMRL_CROSS_CHECK_RESULT IN ('AD','RD') AND AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
		%Q_SYSRSN;
		REJECTIND='CC';
	END;

	IF AMRL_PRE_VAL_RESULT IN ('AD', 'RD') AND AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
		%Q_SYSRSN;
		REJECTIND='PV';
	END;




IF AMRL_APP_SCORE_RESULT='AD' THEN DO;
		WHATREASON='XX';
END;

IF AMRL_APP_SCORE_RESULT='RD' OR AMRL_APP_SCORE_RESULT='RC' THEN DO;
		WHATREASON=AMRL_USER_FIELD_ALPHA_3_1_4;
END;




IF AMRL_JUDGEMENT_RESULT IN ('AD','RD') AND AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
	%Q_SYSRSN;
END;




/*TO FINALIZE REASON CODES FOR DECLINE APPLICATIONS*/
IF AMRL_USER_FIELD_ALPHA_3_1_4 NE ' ' THEN WHATREASON=AMRL_USER_FIELD_ALPHA_3_1_4;
END;

/*DEFINE CANCELLED APPLICATIONS*/
IF (AMRL_JUDGEMENT_STATUS='D' AND AMRL_JUDGEMENT_OPER='SYS' AND AMRL_JUDGEMENT_RESULT='AC') THEN DO;
	AMRL_ACCEPT_DECLINE_IND='C';
	WHATREASON='T04'; /*CANCELLED AT JUDGEMENT*/
END;

IF(AMRL_VERFICATION_STATUS='D' AND AMRL_USER_FIELD_ALPHA_3_1_4 EQ ' ') THEN DO;
	AMRL_ACCEPT_DECLINE_IND='C';
	WHATREASON='T05'; /*CANCELLED AT VERIFICATION*/
END;

IF (AMRL_EDIT_STATUS='D' AND AMRL_EDIT_OPER=' ') THEN DO;
	AMRL_ACCEPT_DECLINE_IND='C';
	WHATREASON='T06'; /*CANCELLED AT EDIT*/
END;

IF (AMRL_ACCEPT_DECLINE_IND='D') AND SUBSTR(AMRL_USER_FIELD_ALPHA_3_1_4,1,1) IN ('W') THEN DO;
	AMRL_ACCEPT_DECLINE_IND='C';
	IF AMRL_USER_FIELD_ALPHA_3_1_4 NE ' ' THEN WHATREASON=AMRL_USER_FIELD_ALPHA_3_1_4;
END;




IF AMRL_ACCEPT_DECLINE_IND='A' THEN DO;
	*APPROVE BY CR;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E38','E41','E54','X38','X41','X54') THEN DO;
		APP_STATUS="(1) CR_APPR"; *APPLICANT PROFILE;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E28','E58','X28','X58') THEN DO;
		APP_STATUS="(1) CR_APPR"; *EXTERNAL CHECKS;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E34','E55','X34','X55') THEN DO;
		APP_STATUS="(1) CR_APPR"; *INTERNAL CHECKS;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E56','E60','E46','X56','X60','X46') THEN DO;
		APP_STATUS="(1) CR_APPR"; *SPECIAL ARRANGEMENT;
	END;

	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E11','X01','X02','X03','X04','X05','X06') THEN DO;
		APP_STATUS="(1) CR_APPR"; 	/*newly added wef from sep 2016; */
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('K01') THEN DO;		
		APP_STATUS="(1) CR_APPR"; 	/*for reinstatement only */
	END;
END;

/*FOR DECLINE*/
*DECLINE BY CR;
IF AMRL_ACCEPT_DECLINE_IND='D' THEN DO;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J62','J03') THEN DO;
		APP_STATUS="(2) CR_DECL"; *APPLICANT PROFILE;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J19') THEN DO;
		APP_STATUS="(2) CR_DECL"; *MUE;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J08','J23','J64','J21') THEN DO;
		APP_STATUS="(2) CR_DECL"; *EXTERNAL CHECKS;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J05','J55','J06','J53','J16','J51','J63','J15','J04', 'J07') THEN DO; /*EZ ADDED J07 ON 30042015*/
		APP_STATUS="(2) CR_DECL"; *INTERNAL CHECKS;
	END;
END;

*DECLINE BY T&O ;
IF AMRL_ACCEPT_DECLINE_IND='D' THEN DO;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('DA','DI','NA','J69','J70','RY') THEN DO;
		APP_STATUS="(3) T&O_DECL"; *APPLICANT PROFILE;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J14','J65','J66') THEN DO;
		APP_STATUS="(3) T&O_DECL"; *CAUTION LIST;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J01','J10') THEN DO;
		APP_STATUS="(3) T&O_DECL"; *DATA VERIFICATION;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('DP','J20','J25','J26','J27','J28','J54','J60','J68','J67','J61') THEN DO; 
		APP_STATUS="(3) T&O_DECL"; *INTERNAL CHECKS;
	END;
END;

/*
*EXISTING CODE (WITHOUT APR QUEUE);
FORMAT SYSTEM $15.;

IF SUBSTR(APP_STATUS,5,2)='CR' THEN SYSTEM='2.CREDIT REVIEW';
	ELSE IF AMRL_DECISION_OPER='SYS' THEN SYSTEM='1.SYSTEM';
	ELSE IF (WHATREASON='A09' AND AMRL_CROSS_CHECK_RESULT NE 'RD') THEN SYSTEM='1.SYSTEM';
	ELSE SYSTEM='3. T&O';

IF SYSTEM IN ('1.SYSTEM','3. T&O') THEN SYSTEM_GRP='1.SYSTEM';
	ELSE SYSTEM_GRP='2.CREDIT REVIEW';
*/

/* TO IDENTIFY SYSTEM_GRP */
	FORMAT SYSTEM_GRP $16.;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E11','X01','X02','X03','X04','X05','X06','X07','X08','X09','X10',
		'J62','J03','J19','J08','J64','J23','J21','J05','J55','J06','J53','J16','J51','J63','J15','J04',
		'J07','J12','E12','K01','K12','K30','K60') 
		THEN SYSTEM_GRP='2.CREDIT REVIEW';
/* TO CATER FOR CASES WHERE FINAL APPROVAL AT CREDIT REVIEW BUT WITHOUT APPROVE/DECLINE CODE ENTERED */
/*	ELSE IF AMRL_USER_FIELD_ALPHA_3_1_4 = "" AND AMRL_DECISION_OPER IN ("4JU","GS2","ML7","PH8","TEH") 
		THEN SYSTEM_GRP='2.CREDIT REVIEW'; */
	ELSE IF AMRL_DECISION_OPER = ""
		THEN SYSTEM_GRP='1.SYSTEM'; 
	ELSE SYSTEM_GRP='1.SYSTEM'; 

/*Referral Reason - 14 APR 2020 */
/*
IF SYSTEM_GRP = '2.CREDIT REVIEW' AND AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
	%N_REFRSN; END;
	ELSE IF SYSTEM_GRP = '2.CREDIT REVIEW' AND AMRL_DATE_ENTERED_EDIT LT '15JAN2015'D THEN DO;
	%O_REFRSN; END;

REASON_DESCRIP_REF=PUT(RSNGRP_REF,$RSNCDE.);
*/

/*TO COUNT*/
LENGTH ACCPCNT DECLCNT PENDCNT PROCNT CANLCNT ENTERCNT 3.;
ACCPCNT=0;DECLCNT=0;CANLCNT=0;PENDCNT=0;ENTERCNT=0;

IF AMRL_ACCEPT_DECLINE_IND='A' THEN ACCPCNT=1;
	ELSE IF AMRL_ACCEPT_DECLINE_IND='D' THEN DECLCNT=1;
	ELSE IF AMRL_ACCEPT_DECLINE_IND='C' THEN CANLCNT=1;
	ELSE IF AMRL_ACCEPT_DECLINE_IND=' ' THEN PENDCNT=1;

IF AMRL_DATE_ENTERED_EDIT NE ' ' AND AMRL_DATE_EXITED_EDIT NE ' ' THEN ENTERCNT=1;

IF ACCPCNT=1 OR DECLCNT=1 OR CANLCNT=1 THEN PROCNT=1;
CNT=1;



/*DEFINE DEVIATED APPLICATIONS*/
/*EZ ADDED 30042015*/
IF SUBSTR(AMRL_USER_FIELD_ALPHA_3_1_4,1,1)='X' AND AMRL_ACCEPT_DECLINE_IND='A' THEN DEVIATION="YES";
	ELSE DEVIATION="NO";



FORMAT N_SOURCECDE $80. SOURCE $80.;
N_SOURCECDE=SUBSTR(AMRL_USER_FIELD_ALPHA_10_1_5,5,2);
IF AMRL_DECISION_DATE GE '01JAN2014'D THEN SOURCE=PUT(N_SOURCECDE, $CAMPAIGNA.);
	ELSE IF AMRL_DECISION_DATE LT '01JAN2014'D THEN SOURCE=PUT(N_SOURCECDE, $CAMPAIGNO.);



*NATIONALITY;
IF SUBSTR(AMRL_DRIVER_LICENSE_NBR_1,1,1) IN ('S','T') OR AMRL_USER_FIELD_ALPHA_1_1_3 IN ('Y') THEN NATION_IND="NON-FOREIGNER";
	ELSE NATION_IND="FOREIGNER";



IF WHATREASON in ('E12','J12') THEN DO;
IF AMRL_ACCEPT_DECLINE_IND='A' THEN APP_STATUS="(1) CR_APPR";
ELSE IF AMRL_ACCEPT_DECLINE_IND='D' THEN APP_STATUS="(2) CR_DECL";
PROCESSOR="2.CREDIT";
SYSTEM="2.CREDIT REVIEW";
SYSTEM_GRP="2.CREDIT";
END;


IF WHATREASON IN (' ') AND AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
	%Q_SYSRSN;
END;

RUN;



DATA CDMCARD_E_&YYMM;
	SET temp_CDM_ALL_2;
	WHERE AMRL_ACCEPT_DECLINE_IND IN ('A','C','D'); 

	FORMAT RSNGRP $3.;

IF AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
	IF WHATREASON IN ('N1','N2') THEN RSNGRP='NF';
		ELSE IF WHATREASON IN ('B1','B2','B3') THEN RSNGRP='BG';
		ELSE IF WHATREASON IN ('P1','P2') THEN RSNGRP='PV';
		ELSE IF WHATREASON IN ('P3','P4','P5','PV') THEN RSNGRP='PH';
		ELSE IF WHATREASON IN ('N3','N4','N5') THEN RSNGRP='NH';
		ELSE IF WHATREASON IN ('N6','N7','N8','N9') THEN RSNGRP='NB';
		ELSE RSNGRP=WHATREASON;
END;



FORMAT TYPE_A $80. TYPE_DESCRIP $80. REASON_DESCRIP $80. SYSTEM_GRP $80. ISS_IND $80. DECISION $80. GROUP $80. GROUP_N $80.;

	IF TYPE IN ('312') AND AMRL_USER_FIELD_ALPHA_5_1_2 NOT IN ('D201','D202','P101','P102') THEN TYPE_A='312-CARD BT';
		ELSE IF TYPE IN ('312') AND AMRL_USER_FIELD_ALPHA_5_1_2 IN ('D201','D202','P101','P102') THEN TYPE_A='312-CARD FT';
		ELSE TYPE_A=TYPE;

		IF TYPE IN ('312','311','313','321','314','399','316','333','377','900') THEN ISS_IND="NON-ISSUANCE";
		ELSE ISS_IND="ISSUANCE"; 

	IF AMRL_ACCEPT_DECLINE_IND IN ('A') THEN DECISION="1. APPROVED";
		ELSE IF AMRL_ACCEPT_DECLINE_IND IN ('C') THEN DECISION="2. CANCELLED";
		ELSE IF AMRL_ACCEPT_DECLINE_IND IN ('D') THEN DECISION="3. DECLINED";
		ELSE DECISION="4. PENDING";

	IF AMRL_ACCEPT_DECLINE_IND IN ('A') AND AMRL_USER_FIELD_ALPHA_3_1_4 NOT IN (' ') THEN WHATREASON=AMRL_USER_FIELD_ALPHA_3_1_4;

	PROCESSOR=PUT(UPCASE(SYSTEM_GRP),100.);
	IF WHATREASON IN (' ') THEN REASON_DESCRIP="<BLANK>";	GROUP=PUT(WHATREASON,$RSNCAT.);
	GROUP_N=PUT(WHATREASON,$RSNCAT_N.);
	PROCESSOR=PUT(UPCASE(SYSTEM_GRP),100.);
	TYPE_DESCRIP=PUT(TYPE_A,$CDTYPE.);
	REASON_DESCRIP=PUT(RSNGRP,$RSNCDE.);
	DEC_MTH=PUT(AMRL_DECISION_DATE, /*MONYY5.*/YYMM7.);
	PRODUCT=PUT(UPCASE(PDT),100.);
	PRODUCT_GRP=PUT(UPCASE(PROCESS_GRP),100.);



	IF WHATREASON IN (' ') THEN REASON_DESCRIP="<BLANK>";


IF (AMRL_DECISION_DATE >= '1May2017'd) AND 
(REASON_DESCRIP = 'NA - FOREIGNER EMPLOYMENT PASS/NATIONALITY CHECKS') AND 
(DECISION ='3. DECLINED') 
THEN DO ; 

DECISION ="2. CANCELLED" ;
AMRL_ACCEPT_DECLINE_IND='C';
CANLCNT=1;

END;


RUN;


/**************************************************/
/**************************************************/
/**************************************************/
/**************************************************/
/**************************************************/
/**************************************************/
/**************************************************/
/**************************************************/
/**************************************************/
/**************************************************/
/**************************************************/
/**************************************************/
/**************************************************/

data temp_CDM_OTHERS_1;
set ds_uat./*mth*/cdm&yymm(keep=
ORG
TYPE
APPLICATION
AMRL_NBR_OF_ASSOCS
AMRL_STATUS
AMRL_LAST_MAINT
AMRL_LAST_MAINT_OPER
AMRL_ACCEPT_DECLINE_IND
AMRL_DECISION_DATE
AMRL_DECISION_OPER
AMRL_DATE_ENTERED_EDIT
AMRL_DATE_EXITED_EDIT
AMRL_EDIT_OPER
AMRL_EDIT_STATUS
AMRL_PRE_VAL_OPER
AMRL_PRE_VAL_STATUS
AMRL_PRE_VAL_RESULT
AMRL_APP_SCORE_RESULT
AMRL_VERFICATION_OPER
AMRL_VERFICATION_STATUS
AMRL_VERFICATION_RESULT
AMRL_JUDGEMENT_OPER
AMRL_JUDGEMENT_STATUS
AMRL_JUDGEMENT_RESULT
AMRL_SETUP_OPER
AMRL_SETUP_STATUS
AMRL_DECLINE_REASON_44
AMRL_FULL_NAME_1
AMRL_COUNTRY_1
AMRL_DRIVER_LICENSE_NBR_1
AMRL_USER_FIELD_ALPHA_1_1_3
AMRL_USER_FIELD_ALPHA_10_1_5
AMRL_USER_FIELD_ALPHA_3_1_4
AMRL_USER_FIELD_ALPHA_5_1_2
SMRL_USER_FIELD_ALPHA_23_1_19

AMRL_DECLINE_REASON_1
AMRL_DECLINE_REASON_2
AMRL_DECLINE_REASON_3
AMRL_DECLINE_REASON_4
AMRL_DECLINE_REASON_5
AMRL_DECLINE_REASON_6
AMRL_DECLINE_REASON_7
AMRL_DECLINE_REASON_8
AMRL_DECLINE_REASON_9
AMRL_DECLINE_REASON_10
AMRL_DECLINE_REASON_11
AMRL_DECLINE_REASON_12
AMRL_DECLINE_REASON_13
AMRL_DECLINE_REASON_14
AMRL_DECLINE_REASON_15
AMRL_DECLINE_REASON_16
AMRL_DECLINE_REASON_17
AMRL_DECLINE_REASON_18
AMRL_DECLINE_REASON_19
AMRL_DECLINE_REASON_20
AMRL_DECLINE_REASON_21
AMRL_DECLINE_REASON_22
AMRL_DECLINE_REASON_23
AMRL_DECLINE_REASON_24
AMRL_DECLINE_REASON_25
AMRL_DECLINE_REASON_26
AMRL_DECLINE_REASON_27
AMRL_DECLINE_REASON_28
AMRL_DECLINE_REASON_29
AMRL_DECLINE_REASON_30
AMRL_DECLINE_REASON_31
AMRL_DECLINE_REASON_32
AMRL_DECLINE_REASON_33
AMRL_DECLINE_REASON_34
AMRL_DECLINE_REASON_35
AMRL_DECLINE_REASON_36
AMRL_DECLINE_REASON_37
AMRL_DECLINE_REASON_38
AMRL_DECLINE_REASON_39
AMRL_DECLINE_REASON_40
AMRL_DECLINE_REASON_41
AMRL_DECLINE_REASON_42
AMRL_DECLINE_REASON_43
AMRL_DECLINE_REASON_44
AMRL_DECLINE_REASON_45
AMRL_DECLINE_REASON_46
AMRL_DECLINE_REASON_47
AMRL_DECLINE_REASON_48
AMRL_DECLINE_REASON_49
AMRL_DECLINE_REASON_50
AMRL_DECLINE_REASON_51
AMRL_DECLINE_REASON_52
AMRL_DECLINE_REASON_53
AMRL_DECLINE_REASON_54
AMRL_DECLINE_REASON_55
AMRL_DECLINE_REASON_56
AMRL_DECLINE_REASON_57
AMRL_DECLINE_REASON_58
AMRL_DECLINE_REASON_59
AMRL_DECLINE_REASON_60
AMRL_DECLINE_REASON_61
AMRL_DECLINE_REASON_62
AMRL_DECLINE_REASON_63
AMRL_DECLINE_REASON_64
AMRL_DECLINE_REASON_65
AMRL_DECLINE_REASON_66
AMRL_DECLINE_REASON_67
AMRL_DECLINE_REASON_68
AMRL_DECLINE_REASON_69
AMRL_DECLINE_REASON_70
AMRL_DECLINE_REASON_71
AMRL_DECLINE_REASON_72
AMRL_DECLINE_REASON_73
AMRL_DECLINE_REASON_74
AMRL_DECLINE_REASON_75
AMRL_DECLINE_REASON_76
AMRL_DECLINE_REASON_77
AMRL_DECLINE_REASON_78
AMRL_DECLINE_REASON_79
AMRL_DECLINE_REASON_80
AMRL_DECLINE_REASON_81
AMRL_DECLINE_REASON_82
AMRL_DECLINE_REASON_83
AMRL_DECLINE_REASON_84
AMRL_DECLINE_REASON_85
AMRL_DECLINE_REASON_86
AMRL_DECLINE_REASON_87
AMRL_DECLINE_REASON_88
AMRL_DECLINE_REASON_89
AMRL_DECLINE_REASON_90
AMRL_DECLINE_REASON_91
AMRL_DECLINE_REASON_92
AMRL_DECLINE_REASON_93
AMRL_DECLINE_REASON_94
AMRL_DECLINE_REASON_95
AMRL_DECLINE_REASON_96
AMRL_DECLINE_REASON_97
AMRL_DECLINE_REASON_98
AMRL_DECLINE_REASON_99
AMRL_DECLINE_REASON_100
AMRL_DECLINE_REASON_101
AMRL_DECLINE_REASON_102
AMRL_DECLINE_REASON_103
AMRL_DECLINE_REASON_104
AMRL_DECLINE_REASON_105
AMRL_DECLINE_REASON_106
AMRL_DECLINE_REASON_107
AMRL_DECLINE_REASON_108
AMRL_DECLINE_REASON_109
AMRL_DECLINE_REASON_110
AMRL_DECLINE_REASON_111
AMRL_DECLINE_REASON_112
AMRL_DECLINE_REASON_113
AMRL_DECLINE_REASON_114
AMRL_DECLINE_REASON_115
AMRL_DECLINE_REASON_116
AMRL_DECLINE_REASON_117
AMRL_DECLINE_REASON_118
AMRL_DECLINE_REASON_119
AMRL_DECLINE_REASON_120
AMRL_DECLINE_REASON_121
AMRL_DECLINE_REASON_122
AMRL_DECLINE_REASON_123
AMRL_DECLINE_REASON_124
AMRL_DECLINE_REASON_125
AMRL_DECLINE_REASON_126
AMRL_DECLINE_REASON_127
AMRL_DECLINE_REASON_128
AMRL_DECLINE_REASON_129
AMRL_DECLINE_REASON_130
AMRL_DECLINE_REASON_131
AMRL_DECLINE_REASON_132
AMRL_DECLINE_REASON_133
AMRL_DECLINE_REASON_134
AMRL_DECLINE_REASON_135
AMRL_DECLINE_REASON_136
AMRL_DECLINE_REASON_137
AMRL_DECLINE_REASON_138
AMRL_DECLINE_REASON_139
AMRL_DECLINE_REASON_140
AMRL_DECLINE_REASON_141
AMRL_DECLINE_REASON_142
AMRL_DECLINE_REASON_143
AMRL_DECLINE_REASON_144
AMRL_DECLINE_REASON_145
AMRL_DECLINE_REASON_146
AMRL_DECLINE_REASON_147
AMRL_DECLINE_REASON_148
AMRL_DECLINE_REASON_149
AMRL_DECLINE_REASON_150
AMRL_DECLINE_REASON_151
AMRL_DECLINE_REASON_152
AMRL_DECLINE_REASON_153
AMRL_DECLINE_REASON_154
AMRL_DECLINE_REASON_155
AMRL_DECLINE_REASON_156
AMRL_DECLINE_REASON_157
AMRL_DECLINE_REASON_158
AMRL_DECLINE_REASON_159
AMRL_DECLINE_REASON_160
AMRL_DECLINE_REASON_161
AMRL_DECLINE_REASON_162
AMRL_DECLINE_REASON_163
AMRL_DECLINE_REASON_164
AMRL_DECLINE_REASON_165
AMRL_DECLINE_REASON_166
AMRL_DECLINE_REASON_167
AMRL_DECLINE_REASON_168
AMRL_DECLINE_REASON_169
AMRL_DECLINE_REASON_170
AMRL_DECLINE_REASON_171
AMRL_DECLINE_REASON_172
AMRL_DECLINE_REASON_173
AMRL_DECLINE_REASON_174
AMRL_DECLINE_REASON_175
AMRL_DECLINE_REASON_176
AMRL_DECLINE_REASON_177
AMRL_DECLINE_REASON_178
AMRL_DECLINE_REASON_179
AMRL_DECLINE_REASON_180
AMRL_DECLINE_REASON_181
AMRL_DECLINE_REASON_182
AMRL_DECLINE_REASON_183
AMRL_DECLINE_REASON_184
AMRL_DECLINE_REASON_185
AMRL_DECLINE_REASON_186
AMRL_DECLINE_REASON_187
AMRL_DECLINE_REASON_188
AMRL_DECLINE_REASON_189
AMRL_DECLINE_REASON_190
AMRL_DECLINE_REASON_191
AMRL_DECLINE_REASON_192
AMRL_DECLINE_REASON_193
AMRL_DECLINE_REASON_194
AMRL_DECLINE_REASON_195
AMRL_DECLINE_REASON_196
AMRL_DECLINE_REASON_197
AMRL_DECLINE_REASON_198
AMRL_DECLINE_REASON_199
AMRL_DECLINE_REASON_200
AMRL_DECLINE_REASON_201
AMRL_DECLINE_REASON_202
AMRL_DECLINE_REASON_203
AMRL_DECLINE_REASON_204
AMRL_DECLINE_REASON_205
AMRL_DECLINE_REASON_206
AMRL_DECLINE_REASON_207
AMRL_DECLINE_REASON_208
AMRL_DECLINE_REASON_209
AMRL_DECLINE_REASON_210
AMRL_DECLINE_REASON_211
AMRL_DECLINE_REASON_212
AMRL_DECLINE_REASON_213
AMRL_DECLINE_REASON_214
AMRL_DECLINE_REASON_215
AMRL_DECLINE_REASON_216
AMRL_DECLINE_REASON_217
AMRL_DECLINE_REASON_218
AMRL_DECLINE_REASON_219
AMRL_DECLINE_REASON_220
AMRL_DECLINE_REASON_221
AMRL_DECLINE_REASON_222
AMRL_DECLINE_REASON_223
AMRL_DECLINE_REASON_224
AMRL_DECLINE_REASON_225
AMRL_DECLINE_REASON_226
AMRL_DECLINE_REASON_227
AMRL_DECLINE_REASON_228
AMRL_DECLINE_REASON_229
AMRL_DECLINE_REASON_230
AMRL_DECLINE_REASON_231
AMRL_DECLINE_REASON_232
AMRL_DECLINE_REASON_233
AMRL_DECLINE_REASON_234
AMRL_DECLINE_REASON_235
AMRL_DECLINE_REASON_236
AMRL_DECLINE_REASON_237
AMRL_DECLINE_REASON_238
AMRL_DECLINE_REASON_239
AMRL_DECLINE_REASON_240
AMRL_DECLINE_REASON_241
AMRL_DECLINE_REASON_242
AMRL_DECLINE_REASON_243
AMRL_DECLINE_REASON_244
AMRL_DECLINE_REASON_245
AMRL_DECLINE_REASON_246
AMRL_DECLINE_REASON_247
AMRL_DECLINE_REASON_248
AMRL_DECLINE_REASON_249

AMRL_CREDIT_LIMIT
);

LENGTH AMRL_USER_FIELD_ALPHA_3_1_2 $3.;

where AMRL_DECISION_DATE ge &setStartDT;

proc sort tagsort data=temp_CDM_OTHERS_1 out=temp_CDM_OTHERS_1_2; 
by APPLICATION AMRL_DECISION_DATE;
run;



DATA temp_CDM_OTHERS_2;
	SET temp_CDM_OTHERS_1;

	IF TYPE NOT IN ('200','300','901','902','911','912','914','400','500') AND ORG='100';

	IF MONTH(AMRL_DECISION_DATE)ge &MMM AND YEAR(AMRL_DECISION_DATE)ge &YYYY;

/**************REQUEST FOR APPROVAL TO CORRECT APPROVAL CODE ERROR; DC Deviation Rate booked in Jan & Feb 2020.**************/

	IF APPLICATION IN 
	(
	'2019364165913',
	'2019364090839',
	'2020014134242',
	'2020015154229',
	'2020020153257',
	'2020015124529',
	'2020021134706',
	'2020023165155',
	'2020028153657',
	'2020023100754',
	'2020028134425',
	'2020028163657',
	'2020030150410',
	'2020030172714',
	'2020036112953',
	'2020037151357',
	'2020037181215',
	'2020041112450',
	'2020041172008',
	'2020044105106',
	'2020050133222',
	'2020050143048',
	'2020056095006',
	'2020057093429'
	) 
	THEN DO;	
	AMRL_USER_FIELD_ALPHA_3_1_4 = 'E11';
	END;
	

	LENGTH PDT $10.;
	FORMAT PROCESS PROCESS_GRP $20.;
	
	IF SUBSTR(TYPE,1,1)='1' THEN 										PDT="RENO";
		ELSE IF TYPE IN ('469','492') THEN 								PDT="POSB";
		ELSE IF TYPE IN ('460') THEN 									PDT="PAYDOWN ASSISTANCE"; /*Temporary created ANZ portfolio in 2018. Code 460 was originally POSB Loan Assist*/	
		ELSE IF TYPE IN ('490','491') THEN								PDT="POSB LA +";
		ELSE IF TYPE IN ('470') THEN									PDT="REPAYMENT ASSISTANT SCHEME (RAS)"; /*EZ ADDED 30042015*/
		ELSE IF TYPE IN ('850') THEN									PDT="MARGIN TRADING";
		ELSE IF TYPE IN ('600','650','700','800') THEN			        PDT="STUDY ASSIST";
		ELSE IF TYPE IN ('700','710','720','730','740','750') THEN	    PDT="TFL";
		ELSE IF TYPE IN ('466') THEN									PDT="TOTEBOARD";
		ELSE IF TYPE IN ('465') THEN 									PDT="MED LOAN";
		ELSE IF TYPE IN ('471') THEN 									PDT="DEBT CONSOLIDATION LOAN"; 	/*Newly added Jan17*/
		ELSE															PDT="CASHLINE";


	IF TYPE IN ('400','410','417','419','421','422','433','438','482','500','413','414') /*Newly added 413 and 414 on Jan17*/ 
	THEN	PROCESS="1. NEW APPLICATION";
		ELSE IF TYPE IN ('450','451','452','444','458') THEN								PROCESS="3. LINE MGT"; /*Newly added 458 on May20*/
		ELSE IF TYPE IN ('480','481','483') THEN 									PROCESS="4. CASHLINE PLUS";
		ELSE IF TYPE IN ('412') THEN												PROCESS="5. BT/FT";
		ELSE IF TYPE IN ('100','110','113','850','600','650','700','800') THEN		PROCESS="6. CREDIT REVIEW";
		ELSE IF TYPE IN ('411','418','420','413','414')  THEN 						PROCESS="6. INSTALMENT LOAN"; /*Newly added 413 and 414 on Jan17*/

		ELSE IF TYPE IN ('469') THEN	 											PROCESS="1. POSB LA";
		ELSE IF TYPE IN ('460') THEN 												PROCESS="1. PAYDOWN ASSISTANCE"; /*Temporary created ANZ portfolio in 2018. Code 460 was originally POSB Loan Assist*/
		ELSE IF TYPE IN ('492') THEN												PROCESS="2. FAST PROCESSING";
		ELSE IF TYPE IN ('490','491') THEN											PROCESS="3. POSB LA PLUS";
		ELSE IF TYPE IN ('470') THEN												PROCESS="4. REPAYMENT ASSISTANT SCHEME (RAS)"; /*EZ ADDED 30042015*/
		ELSE 																		PROCESS="2. OTHERS";

	LENGTH WHATREASON $3. REASON_DESCRIP $80./*CATEGORY $32.*/;

	/*DEFINE ACCEPTED APPLICATIONS*/
	IF AMRL_ACCEPT_DECLINE_IND='A' THEN DO;
		IF AMRL_USER_FIELD_ALPHA_3_1_4 NE ' ' THEN WHATREASON=AMRL_USER_FIELD_ALPHA_3_1_4;
	END;



	LENGTH REJECTIND$2.;

IF AMRL_ACCEPT_DECLINE_IND='D' THEN DO;
	IF AMRL_CROSS_CHECK_RESULT IN ('AD','RD') AND AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
		%Q_SYSRSN;
		REJECTIND='CC';
	END;

	IF AMRL_PRE_VAL_RESULT IN ('AD', 'RD') AND AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
		%Q_SYSRSN;
		REJECTIND='PV';
	END;



IF AMRL_APP_SCORE_RESULT='AD' THEN DO;
		WHATREASON='XX';
END;

IF AMRL_APP_SCORE_RESULT='RD' OR AMRL_APP_SCORE_RESULT='RC' THEN DO;
		WHATREASON=AMRL_USER_FIELD_ALPHA_3_1_4;
END;



IF AMRL_JUDGEMENT_RESULT IN ('AD','RD') AND AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
	%Q_SYSRSN;
END;



	/*** TO FINALIZE REASON CODES FOR DECLINE APPLICATIONS ***/
IF AMRL_USER_FIELD_ALPHA_3_1_4 NE ' ' THEN WHATREASON=AMRL_USER_FIELD_ALPHA_3_1_4;
END;

		/*DEFINE CANCELLED APPLICATIONS*/
IF (AMRL_JUDGEMENT_STATUS='D' AND AMRL_JUDGEMENT_OPER='SYS' AND AMRL_JUDGEMENT_RESULT='AC') THEN DO;
	AMRL_ACCEPT_DECLINE_IND='C';
	WHATREASON='T04'; /*CANCELLED AT JUDGEMENT*/
END;

IF(AMRL_VERFICATION_STATUS='D' AND AMRL_USER_FIELD_ALPHA_3_1_4 EQ ' ') THEN DO;
	AMRL_ACCEPT_DECLINE_IND='C';
	WHATREASON='T05'; /*CANCELLED AT VERIFICATION*/
END;

IF (AMRL_EDIT_STATUS='D' AND AMRL_EDIT_OPER=' ') THEN DO;
	AMRL_ACCEPT_DECLINE_IND='C';
	WHATREASON='T06'; /*CANCELLED AT EDIT*/
END;

IF (AMRL_ACCEPT_DECLINE_IND='D') AND SUBSTR(AMRL_USER_FIELD_ALPHA_3_1_4,1,1) IN ('W') THEN DO;
	AMRL_ACCEPT_DECLINE_IND='C';
	IF AMRL_USER_FIELD_ALPHA_3_1_4 NE ' ' THEN WHATREASON=AMRL_USER_FIELD_ALPHA_3_1_4;
END;


IF AMRL_ACCEPT_DECLINE_IND='A' THEN DO;
	*APPROVE BY CR;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E38','E41','E54','X38','X41','X54') THEN DO;
		APP_STATUS="(1) CR_APPR"; *APPLICANT PROFILE;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E28','E58','X28','X58') THEN DO;
		APP_STATUS="(1) CR_APPR"; *EXTERNAL CHECKS;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E34','E55','X34','X55') THEN DO;
		APP_STATUS="(1) CR_APPR"; *INTERNAL CHECKS;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E56','E60','E46','X56','X60','X46') THEN DO;
		APP_STATUS="(1) CR_APPR"; *SPECIAL ARRANGEMENT;
	END;

	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E11','X01','X02','X03','X04','X05','X06') THEN DO;
		APP_STATUS="(1) CR_APPR"; 	/*newly added wef from sep 2016; */
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('K01') THEN DO;		
		APP_STATUS="(1) CR_APPR"; 	/*for reinstatement only */
	END;
END;

/*FOR DECLINE*/
*DECLINE BY CR;
IF AMRL_ACCEPT_DECLINE_IND='D' THEN DO;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J62','J03') THEN DO;
		APP_STATUS="(2) CR_DECL"; *APPLICANT PROFILE;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J19') THEN DO;
		APP_STATUS="(2) CR_DECL"; *MUE;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J08','J23','J64','J21') THEN DO;
		APP_STATUS="(2) CR_DECL"; *EXTERNAL CHECKS;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J05','J55','J06','J53','J16','J51','J63','J15','J04', 'J07') THEN DO; /*EZ ADDED J07 ON 30042015*/
		APP_STATUS="(2) CR_DECL"; *INTERNAL CHECKS;
	END;
END;

*DECLINE BY T&O ;
IF AMRL_ACCEPT_DECLINE_IND='D' THEN DO;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('DA','DI','NA','J69','J70','RY') THEN DO;
		APP_STATUS="(3) T&O_DECL"; *APPLICANT PROFILE;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J14','J65','J66') THEN DO;
		APP_STATUS="(3) T&O_DECL"; *CAUTION LIST;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('J01','J10') THEN DO;
		APP_STATUS="(3) T&O_DECL"; *DATA VERIFICATION;
	END;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('DP','J20','J25','J26','J27','J28','J54','J60','J68','J67','J61') THEN DO; 
		APP_STATUS="(3) T&O_DECL"; *INTERNAL CHECKS;
	END;
END;



/*
*EXISTING CODE (WITHOUT APR QUEUE);
FORMAT SYSTEM $15.;

IF SUBSTR(APP_STATUS,5,2)='CR' THEN SYSTEM='2.CREDIT REVIEW';
	ELSE IF AMRL_DECISION_OPER='SYS' THEN SYSTEM='1.SYSTEM';
	ELSE IF (WHATREASON='A09' AND AMRL_CROSS_CHECK_RESULT NE 'RD') THEN SYSTEM='1.SYSTEM';
	ELSE SYSTEM='3. T&O';

IF SYSTEM IN ('1.SYSTEM','3. T&O') THEN SYSTEM_GRP='1.SYSTEM';
	ELSE SYSTEM_GRP='2.CREDIT REVIEW';
*/

/* TO IDENTIFY SYSTEM_GRP */
	FORMAT SYSTEM_GRP $16.;
	IF AMRL_USER_FIELD_ALPHA_3_1_4 IN ('E11','X01','X02','X03','X04','X05','X06','X07','X08','X09','X10',
		'J62','J03','J19','J08','J64','J23','J21','J05','J55','J06','J53','J16','J51','J63','J15','J04',
		'J07','J12','E12','K01','K12','K30','K60') 
		THEN SYSTEM_GRP='2.CREDIT REVIEW';
/* TO CATER FOR CASES WHERE FINAL APPROVAL AT CREDIT REVIEW BUT WITHOUT APPROVE/DECLINE CODE ENTERED */
/*	ELSE IF AMRL_USER_FIELD_ALPHA_3_1_4 = "" AND AMRL_DECISION_OPER IN ("4JU","GS2","ML7","PH8","TEH") 
		THEN SYSTEM_GRP='2.CREDIT REVIEW'; */
	ELSE IF AMRL_DECISION_OPER = ""
		THEN SYSTEM_GRP='1.SYSTEM'; 
	ELSE SYSTEM_GRP='1.SYSTEM'; 

/*Referral Reason - 14 APR 2020 */
/*
IF SYSTEM_GRP = '2.CREDIT REVIEW' AND AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
	%N_REFRSN; END;
	ELSE IF SYSTEM_GRP = '2.CREDIT REVIEW' AND AMRL_DATE_ENTERED_EDIT LT '15JAN2015'D THEN DO;
	%O_REFRSN; END;

REASON_DESCRIP_REF=PUT(RSNGRP_REF,$RSNCDE.);
*/

/*TO COUNT*/
LENGTH ACCPCNT DECLCNT PENDCNT PROCNT CANLCNT ENTERCNT 3.;
ACCPCNT=0;DECLCNT=0;CANLCNT=0;PENDCNT=0;ENTERCNT=0;

IF AMRL_ACCEPT_DECLINE_IND='A' THEN ACCPCNT=1;
	ELSE IF AMRL_ACCEPT_DECLINE_IND='D' THEN DECLCNT=1;
	ELSE IF AMRL_ACCEPT_DECLINE_IND='C' THEN CANLCNT=1;
	ELSE IF AMRL_ACCEPT_DECLINE_IND=' ' THEN PENDCNT=1;

IF AMRL_DATE_ENTERED_EDIT NE ' ' AND AMRL_DATE_EXITED_EDIT NE ' ' THEN ENTERCNT=1;

IF ACCPCNT=1 OR DECLCNT=1 OR CANLCNT=1 THEN PROCNT=1;
CNT=1;



/*DEFINE DEVIATED APPLICATIONS*/
/*EZ ADDED 30042015*/
IF SUBSTR(AMRL_USER_FIELD_ALPHA_3_1_4,1,1)='X' AND AMRL_ACCEPT_DECLINE_IND='A' THEN DEVIATION="YES";
	ELSE DEVIATION="NO";



FORMAT N_SOURCECDE $80. SOURCE $80.;
N_SOURCECDE=SUBSTR(AMRL_USER_FIELD_ALPHA_10_1_5,5,2);
IF AMRL_DECISION_DATE GE '01JAN2014'D THEN SOURCE=PUT(N_SOURCECDE, $CAMPAIGNA.);
	ELSE IF AMRL_DECISION_DATE LT '01JAN2014'D THEN SOURCE=PUT(N_SOURCECDE, $CAMPAIGNO.);



*NATIONALITY;
IF SUBSTR(AMRL_DRIVER_LICENSE_NBR_1,1,1) IN ('S','T') OR AMRL_USER_FIELD_ALPHA_1_1_3 IN ('Y') THEN NATION_IND="NON-FOREIGNER";
	ELSE NATION_IND="FOREIGNER";



IF WHATREASON IN (' ') AND AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
	%Q_SYSRSN;
END;


IF WHATREASON IN (' ') THEN REASON_DESCRIP="<BLANK>";


IF WHATREASON in ('E12','J12') THEN DO;
IF AMRL_ACCEPT_DECLINE_IND='A' THEN APP_STATUS="(1) CR_APPR";
ELSE IF AMRL_ACCEPT_DECLINE_IND='D' THEN APP_STATUS="(2) CR_DECL";
PROCESSOR="2.CREDIT";
SYSTEM="2.CREDIT REVIEW";
SYSTEM_GRP="2.CREDIT";
END;

RUN;

DATA CDMOTHERS_E_&YYMM;
	SET temp_CDM_OTHERS_2;
	WHERE AMRL_ACCEPT_DECLINE_IND IN ('A','C','D'); 

	FORMAT RSNGRP $3.;

IF AMRL_DATE_ENTERED_EDIT GE '15JAN2015'D THEN DO;
	IF WHATREASON IN ('N1','N2') THEN RSNGRP='NF';
		ELSE IF WHATREASON IN ('B1','B2','B3') THEN RSNGRP='BG';
		ELSE IF WHATREASON IN ('P1','P2') THEN RSNGRP='PV';
		ELSE IF WHATREASON IN ('P3','P4','P5','PV') THEN RSNGRP='PH';
		ELSE IF WHATREASON IN ('N3','N4','N5') THEN RSNGRP='NH';
		ELSE IF WHATREASON IN ('N6','N7','N8','N9') THEN RSNGRP='NB';
		ELSE RSNGRP=WHATREASON;
END;



FORMAT TYPE_A $80. TYPE_DESCRIP $80. REASON_DESCRIP $80. SYSTEM_GRP $80. ISS_IND $80. DECISION $80. GROUP $80. GROUP_N $80.;
	IF TYPE IN ('312') AND AMRL_USER_FIELD_ALPHA_5_1_2 NOT IN ('D201','D202','P101','P102') THEN TYPE_A='312-CARD BT';
		ELSE IF TYPE IN ('312') AND AMRL_USER_FIELD_ALPHA_5_1_2 IN ('D201','D202','P101','P102') THEN TYPE_A='312-CARD FT';
		ELSE TYPE_A=TYPE;

		IF TYPE IN ('312','311','313','321','314','399','316','333','377','900') THEN ISS_IND="NON-ISSUANCE";
		ELSE ISS_IND="ISSUANCE"; 

	IF AMRL_ACCEPT_DECLINE_IND IN ('A') THEN DECISION="1. APPROVED";
		ELSE IF AMRL_ACCEPT_DECLINE_IND IN ('C') THEN DECISION="2. CANCELLED";
		ELSE IF AMRL_ACCEPT_DECLINE_IND IN ('D') THEN DECISION="3. DECLINED";
		ELSE DECISION="4. PENDING";

	IF AMRL_ACCEPT_DECLINE_IND IN ('A') AND AMRL_USER_FIELD_ALPHA_3_1_4 NOT IN (' ') THEN WHATREASON=AMRL_USER_FIELD_ALPHA_3_1_4;
	PROCESSOR=PUT(UPCASE(SYSTEM_GRP),100.);
	IF WHATREASON IN (' ') THEN REASON_DESCRIP="<BLANK>";	GROUP=PUT(WHATREASON,$RSNCAT.);
	GROUP_N=PUT(WHATREASON,$RSNCAT_N.);
	PROCESSOR=PUT(UPCASE(SYSTEM_GRP),100.);
	TYPE_DESCRIP=PUT(TYPE_A,$CLTYPE.);
	REASON_DESCRIP=PUT(RSNGRP,$RSNCDE.);
	DEC_MTH=PUT(AMRL_DECISION_DATE, /*MONYY5.*/YYMM7.);
	PRODUCT=PUT(UPCASE(PDT),100.);
	PRODUCT_GRP=PUT(UPCASE(PROCESS_GRP),100.);



IF PDT="CASHLINE" THEN DO;

IF (AMRL_DECISION_DATE >= '1May2017'd) AND 
(REASON_DESCRIP = 'NA - FOREIGNER EMPLOYMENT PASS/NATIONALITY CHECKS') AND 
(DECISION ='3. DECLINED') 
THEN DO ; 

DECISION ="2. CANCELLED" ;
AMRL_ACCEPT_DECLINE_IND='C';
CANLCNT=1;

END;
END;

RUN;



data CDM_ALL_3;
set CDMCARD_E_&YYMM CDMOTHERS_E_&YYMM; 
run;



DATA CDM_ALL_4;
	SET CDM_ALL_3;

	%N_RULEFAIL;

RUN;



data CDM_ALL_2;
retain
DEC_MTH
ORG
TYPE
APPLICATION
WHATREASON
DEVIATION
AMRL_NBR_OF_ASSOCS
AMRL_STATUS
AMRL_LAST_MAINT
AMRL_LAST_MAINT_OPER
AMRL_ACCEPT_DECLINE_IND
AMRL_DECISION_DATE
AMRL_DECISION_OPER
AMRL_DATE_ENTERED_EDIT
AMRL_DATE_EXITED_EDIT
AMRL_EDIT_OPER
AMRL_EDIT_STATUS
AMRL_PRE_VAL_OPER
AMRL_PRE_VAL_STATUS
AMRL_PRE_VAL_RESULT
AMRL_APP_SCORE_RESULT
AMRL_VERFICATION_OPER
AMRL_VERFICATION_STATUS
AMRL_VERFICATION_RESULT
AMRL_JUDGEMENT_OPER
AMRL_JUDGEMENT_STATUS
AMRL_JUDGEMENT_RESULT
AMRL_SETUP_OPER
AMRL_SETUP_STATUS

AMRL_FULL_NAME_1
AMRL_COUNTRY_1
AMRL_DRIVER_LICENSE_NBR_1
AMRL_USER_FIELD_ALPHA_10_1_5
AMRL_USER_FIELD_ALPHA_5_1_2
AMRL_USER_FIELD_ALPHA_3_1_2
AMRL_USER_FIELD_ALPHA_3_1_4
AMRL_USER_FIELD_ALPHA_1_1_3
SMRL_USER_FIELD_ALPHA_23_1_19
PRODUCT
PRODUCT_GRP
PROCESS
PROCESS_GRP
PROCESSOR
SYSTEM
SYSTEM_GRP
TYPE_DESCRIP
REASON_DESCRIP
RSNGRP
NATION_IND
PDT
N_SOURCECDE
SOURCE
TYPE_A
ISS_IND
DECISION
GROUP
GROUP_N
REJECTIND
AMRL_CROSS_CHECK_RESULT
FIN_REASON
APP_STATUS
ACCPCNT
DECLCNT
PENDCNT
PROCNT
CANLCNT
ENTERCNT
CNT
RULEFAIL_LIST
AMRL_CREDIT_LIMIT
;


set CDM_ALL_4
(keep=
DEC_MTH
ORG
TYPE
APPLICATION
WHATREASON
AMRL_NBR_OF_ASSOCS
AMRL_STATUS
AMRL_LAST_MAINT
AMRL_LAST_MAINT_OPER
AMRL_ACCEPT_DECLINE_IND
AMRL_DECISION_DATE
AMRL_DECISION_OPER
AMRL_DATE_ENTERED_EDIT
AMRL_DATE_EXITED_EDIT
AMRL_EDIT_OPER
AMRL_EDIT_STATUS
AMRL_PRE_VAL_OPER
AMRL_PRE_VAL_STATUS
AMRL_PRE_VAL_RESULT
AMRL_APP_SCORE_RESULT
AMRL_VERFICATION_OPER
AMRL_VERFICATION_STATUS
AMRL_VERFICATION_RESULT
AMRL_JUDGEMENT_OPER
AMRL_JUDGEMENT_STATUS
AMRL_JUDGEMENT_RESULT
AMRL_SETUP_OPER
AMRL_SETUP_STATUS

AMRL_FULL_NAME_1
AMRL_COUNTRY_1
AMRL_DRIVER_LICENSE_NBR_1
AMRL_USER_FIELD_ALPHA_10_1_5
AMRL_USER_FIELD_ALPHA_5_1_2
AMRL_USER_FIELD_ALPHA_3_1_2
AMRL_USER_FIELD_ALPHA_3_1_4
AMRL_USER_FIELD_ALPHA_1_1_3
SMRL_USER_FIELD_ALPHA_23_1_19
PRODUCT
PRODUCT_GRP
PROCESS
PROCESS_GRP
PROCESSOR
SYSTEM
SYSTEM_GRP
TYPE_DESCRIP
REASON_DESCRIP
RSNGRP
NATION_IND
PDT
N_SOURCECDE
SOURCE
TYPE_A
ISS_IND
DECISION
GROUP
GROUP_N
REJECTIND
AMRL_CROSS_CHECK_RESULT
FIN_REASON
APP_STATUS
ACCPCNT
DECLCNT
PENDCNT
PROCNT
CANLCNT
ENTERCNT
CNT
DEVIATION
RULEFAIL_LIST
AMRL_CREDIT_LIMIT
);

run;

proc sql;
create table CDM_ALL_APPLIST as
Select distinct DEC_MTH, ORG, TYPE, APPLICATION, PROCESS, PROCESSOR, DECISION, AMRL_CREDIT_LIMIT from CDM_ALL_2;
quit;




proc export data=CDM_ALL_2
outfile= "/gccdm/users/cbcfkhg/Reports/Unsecured_FE_Deck.csv"
dbms=csv replace;
run;

proc export data=CDM_ALL_APPLIST
outfile= "/gccdm/users/cbcfkhg/Reports/Unsecured_App_List.csv"
dbms=csv replace;
run;
/**/
/**/
/*proc export data=CDM_ALL_2*/
/*outfile= "/gccdm/users/cbcfpbo/Reports/Unsecured_FE_Deck.csv"*/
/*dbms=csv replace;*/
/*run;*/
/**/
/*proc export data=CDM_ALL_APPLIST*/
/*outfile= "/gccdm/users/cbcfpbo/Reports/Unsecured_App_List.csv"*/
/*dbms=csv replace;*/
/*run;*/


/**************/



/* CHECK
PROC SQL;
   CREATE TABLE WORK.QUERY_FOR_CDM_ALL_2 AS 
   SELECT t1.DEC_MTH, 
          t1.TYPE, 
          t1.APPLICATION, 
          t1.DEVIATION, 
          t1.AMRL_USER_FIELD_ALPHA_3_1_4
      FROM WORK.CDM_ALL_2 t1
      WHERE t1.APPLICATION IN 
 		   (
			'2019364165913',
			'2019364090839',
			'2020014134242',
			'2020015154229',
			'2020020153257',
			'2020015124529',
			'2020021134706',
			'2020023165155',
			'2020028153657',
			'2020023100754',
			'2020028134425',
			'2020028163657',
			'2020030150410',
			'2020030172714',
			'2020036112953',
			'2020037151357',
			'2020037181215',
			'2020041112450',
			'2020041172008',
			'2020044105106',
			'2020050133222',
			'2020050143048',
			'2020056095006',
			'2020057093429'
			); 
QUIT;
*/
